// Einfache Gerichte, angelehnt an beliebte schnelle Rezepte. Nährwerte rechnet die App aus den Zutaten.
// `side: [min, max, schritt]` markiert die Beilage, deren Menge der Planer anpasst, damit der Tag passt.
// Das Bild liegt unter img/<id>.webp.

const REIS = 'Reis waschen und mit so viel Wasser wie immer in den Reiskocher geben.';
const KARTOFFELN = 'Kartoffeln in 2-cm-Würfel schneiden, mit 1 TL Öl und Salz mischen und bei 200 °C in den Airfryer. Sie brauchen etwa 25 Minuten.';
const GEMUESE = 'Das TK-Gemüse für die letzten 10 Minuten dazugeben, zwischendurch einmal schütteln.';
const DURCH = 'Aufschneiden: Innen darf nichts mehr rosa sein.';
const OFEN = 'Passt nicht alles in den Airfryer? Alles aufs Blech, 200 °C Umluft, etwa 30 Minuten.';

export const RECIPES = {
  // ---------- Frühstück ----------
  porridge: {
    name: 'Whey-Porridge', slot: 'fruehstueck', device: 'reiskocher', time: 5, proteins: ['milch'],
    ingredients: [
      { item: 'haferflocken', amount: 70, side: [40, 150] },
      { item: 'whey', amount: 30 },
      { item: 'tk_beeren', amount: 100 },
    ],
    steps: [
      'Haferflocken und Wasser im Verhältnis 1:2 in den Reiskocher, Porridge-Programm starten.',
      'Nach dem Kochen 2–3 Minuten abkühlen lassen, dann das Whey einrühren. Zu heiß klumpt es.',
      'TK-Beeren unterheben, die tauen in der Wärme von selbst auf.',
    ],
    tip: 'Reiskocher nicht randvoll machen, Porridge schäumt hoch.',
  },
  quark_bowl: {
    name: 'Quark-Bowl mit Banane', slot: 'fruehstueck', device: 'ohne', time: 3, proteins: ['milch'],
    ingredients: [
      { item: 'magerquark', amount: 250 },
      { item: 'haferflocken', amount: 40, side: [20, 120] },
      { item: 'banane', amount: 1 },
    ],
    steps: ['Quark in eine Schüssel, Haferflocken drüber, Banane in Scheiben obendrauf.'],
    tip: 'Mit einem Schluck Wasser oder Milch wird der Quark cremiger.',
  },
  shake_fruehstueck: {
    name: 'Bananen-Shake', slot: 'fruehstueck', device: 'ohne', time: 2, proteins: ['milch'],
    ingredients: [
      { item: 'whey', amount: 30 },
      { item: 'milch', amount: 300, side: [200, 600, 50] },
      { item: 'banane', amount: 1 },
    ],
    steps: ['Whey mit der Milch im Shaker schütteln, die Banane dazu essen.'],
  },
  overnight_oats: {
    name: 'Overnight Oats mit Skyr', slot: 'fruehstueck', device: 'ohne', time: 5, proteins: ['milch'],
    ingredients: [
      { item: 'haferflocken', amount: 60, side: [30, 120] },
      { item: 'skyr', amount: 200 },
      { item: 'milch', amount: 100 },
      { item: 'tk_beeren', amount: 100 },
    ],
    steps: [
      'Abends Haferflocken, Skyr und Milch in einem Glas verrühren, die gefrorenen Beeren obendrauf.',
      'Über Nacht in den Kühlschrank. Morgens nur noch umrühren.',
    ],
  },
  ruehrei_brot: {
    name: 'Spinat-Rührei mit Brot', slot: 'fruehstueck', device: 'herd', time: 10, proteins: ['ei'],
    ingredients: [
      { item: 'eier', amount: 3 },
      { item: 'tk_spinat', amount: 100 },
      { item: 'vollkornbrot', amount: 2, side: [1, 5, 1] },
      { item: 'oel', amount: 1 },
    ],
    steps: [
      'Spinat mit dem Öl in der Pfanne auftauen lassen.',
      'Eier verquirlen, salzen, dazugeben und bei mittlerer Hitze stocken lassen.',
      'Mit dem Brot essen.',
    ],
  },
  eiermuffins: {
    name: 'Eiermuffins aus dem Airfryer', slot: 'fruehstueck', device: 'airfryer', time: 10, proteins: ['ei', 'pute'],
    ingredients: [
      { item: 'eier', amount: 3 },
      { item: 'putenaufschnitt', amount: 50, note: 'klein geschnitten' },
      { item: 'tk_paprika', amount: 100 },
      { item: 'vollkornbrot', amount: 1, side: [0, 4, 1] },
    ],
    steps: [
      'Eier verquirlen, salzen, Paprika und Aufschnitt unterrühren.',
      'In Silikon-Muffinförmchen füllen und bei 160 °C etwa 12 Minuten in den Airfryer.',
    ],
    tip: 'Die Muffins halten 3 Tage im Kühlschrank. Gleich die doppelte Menge machen.',
  },
  huettenkaese_brot: {
    name: 'Hüttenkäse-Brote', slot: 'fruehstueck', device: 'ohne', time: 5, proteins: ['milch', 'pute'],
    ingredients: [
      { item: 'vollkornbrot', amount: 2, side: [1, 5, 1] },
      { item: 'huettenkaese', amount: 200 },
      { item: 'putenaufschnitt', amount: 50 },
      { item: 'rohkost', amount: 100 },
    ],
    steps: ['Brote mit Hüttenkäse und Aufschnitt belegen, Rohkost dazu.'],
  },
  skyr_apfel: {
    name: 'Skyr mit Apfel und Nüssen', slot: 'fruehstueck', device: 'ohne', time: 3, proteins: ['milch'],
    ingredients: [
      { item: 'skyr', amount: 300 },
      { item: 'apfel', amount: 1 },
      { item: 'haferflocken', amount: 30, side: [0, 100] },
      { item: 'nuesse', amount: 10 },
    ],
    steps: ['Apfel klein schneiden, mit Haferflocken und gehackten Nüssen auf den Skyr.'],
  },
  laugenbrezel_huettenkaese: {
    name: 'Laugenbrezel mit Hüttenkäse', slot: 'fruehstueck', device: 'ohne', time: 3, proteins: ['milch'], region: 'schwaebisch',
    ingredients: [
      { item: 'laugenbrezel', amount: 1, side: [1, 3, 1] },
      { item: 'huettenkaese', amount: 200 },
      { item: 'rohkost', amount: 100, note: 'Radieschen und Gurke' },
      { item: 'gewuerz', amount: 0, text: 'Schnittlauch, Salz' },
    ],
    steps: ['Brezel aufschneiden, mit Hüttenkäse und Schnittlauch füllen.', 'Radieschen und Gurke dazu.'],
  },

  // ---------- Hauptgerichte ----------
  bowl_haehnchen: {
    name: 'Hähnchen-Reis-Bowl', slot: 'haupt', device: 'reiskocher', time: 10, proteins: ['haehnchen'],
    ingredients: [
      { item: 'reis', amount: 100, side: [50, 250] },
      { item: 'tk_gemuese_mix', amount: 300 },
      { item: 'haehnchenbrust', amount: 180, note: 'in 2-cm-Würfeln' },
      { item: 'sojasauce', amount: 1 },
      { item: 'oel', amount: 2 },
    ],
    steps: [
      REIS,
      'TK-Gemüse gefroren obendrauf, Hähnchenwürfel darauf verteilen. Nicht umrühren.',
      'Sojasauce und Öl darüberträufeln, Reiskocher starten.',
      `Nach dem Kochen das größte Stück ${DURCH.toLowerCase()}`,
    ],
  },
  bowl_thunfisch: {
    name: 'Thunfisch-Reis-Bowl', slot: 'haupt', device: 'reiskocher', time: 5, proteins: ['fisch'],
    ingredients: [
      { item: 'reis', amount: 100, side: [50, 250] },
      { item: 'tk_gemuese_mix', amount: 300 },
      { item: 'thunfisch', amount: 1 },
      { item: 'sojasauce', amount: 1 },
      { item: 'oel', amount: 2 },
    ],
    steps: [
      REIS,
      'TK-Gemüse gefroren obendrauf, Thunfisch darauf verteilen. Nicht umrühren.',
      'Sojasauce und Öl darüberträufeln, Reiskocher starten, danach einmal durchmischen.',
    ],
    tip: 'Dosen mit „Skipjack“ oder „Echter Bonito“ enthalten am wenigsten Quecksilber.',
  },
  teriyaki_haehnchen: {
    name: 'Teriyaki-Hähnchen', slot: 'haupt', device: 'reiskocher', time: 10, proteins: ['haehnchen'],
    ingredients: [
      { item: 'reis', amount: 90, side: [50, 250] },
      { item: 'tk_brokkoli', amount: 250 },
      { item: 'haehnchenbrust', amount: 200, note: 'in Streifen' },
      { item: 'sojasauce', amount: 2 },
      { item: 'honig', amount: 1 },
      { item: 'oel', amount: 1 },
    ],
    steps: [
      'Hähnchen mit Sojasauce, Honig und Öl verrühren und kurz ziehen lassen.',
      REIS,
      'Brokkoli und Hähnchen samt Soße obendrauf, Reiskocher starten.',
      `Danach ${DURCH.toLowerCase()}`,
    ],
  },
  haehnchen_curry: {
    name: 'Hähnchen-Curry', slot: 'haupt', device: 'reiskocher', time: 10, proteins: ['haehnchen'],
    ingredients: [
      { item: 'reis', amount: 90, side: [50, 250] },
      { item: 'tk_gemuese_mix', amount: 250 },
      { item: 'haehnchenbrust', amount: 200, note: 'in Würfeln' },
      { item: 'kokosmilch', amount: 100 },
      { item: 'gewuerz', amount: 0, text: '1 TL Currypulver, Salz' },
    ],
    steps: [
      'Reis waschen und mit etwas weniger Wasser als sonst in den Reiskocher geben.',
      'Gemüse und Hähnchen obendrauf, Kokosmilch mit dem Curry verrühren und darübergießen.',
      `Reiskocher starten, danach umrühren. ${DURCH}`,
    ],
  },
  abend_schenkel_kartoffel: {
    name: 'Hähnchenschenkel mit Kartoffeln', slot: 'haupt', device: 'airfryer', alt: ['ofen'], time: 15, proteins: ['haehnchen'],
    ingredients: [
      { item: 'haehnchenschenkel', amount: 250 },
      { item: 'kartoffeln', amount: 350, side: [200, 900, 50] },
      { item: 'tk_brokkoli', amount: 250 },
      { item: 'oel', amount: 2 },
      { item: 'gewuerz', amount: 0, text: 'Salz, Paprika, Hähnchengewürz' },
    ],
    steps: [KARTOFFELN, 'Hähnchen mit 1 TL Öl und Gewürz einreiben und nach 5 Minuten dazulegen, es braucht etwa 20 Minuten.', GEMUESE, DURCH],
    tip: OFEN,
  },
  abend_brust_reis: {
    name: 'Hähnchenbrust mit Reis', slot: 'haupt', device: 'airfryer', alt: ['ofen'], time: 10, proteins: ['haehnchen'],
    ingredients: [
      { item: 'haehnchenbrust', amount: 250 },
      { item: 'reis', amount: 70, side: [40, 220] },
      { item: 'tk_brokkoli', amount: 250 },
      { item: 'oel', amount: 2 },
      { item: 'gewuerz', amount: 0, text: 'Salz, Paprika, Knoblauch' },
    ],
    steps: [REIS, 'Hähnchenbrust mit Öl und Gewürz einreiben, bei 200 °C etwa 18 Minuten in den Airfryer, nach der Hälfte wenden.', GEMUESE, DURCH],
  },
  abend_schenkel_reis: {
    name: 'Hähnchenschenkel mit Reis und Rosenkohl', slot: 'haupt', device: 'airfryer', alt: ['ofen'], time: 10, proteins: ['haehnchen'],
    ingredients: [
      { item: 'haehnchenschenkel', amount: 250 },
      { item: 'reis', amount: 70, side: [40, 220] },
      { item: 'tk_rosenkohl', amount: 250 },
      { item: 'oel', amount: 1 },
      { item: 'gewuerz', amount: 0, text: 'Salz, Paprika, Hähnchengewürz' },
    ],
    steps: [REIS, 'Hähnchen mit Öl und Gewürz einreiben, bei 200 °C etwa 20 Minuten in den Airfryer, einmal wenden.', GEMUESE, DURCH],
  },
  haehnchen_wrap: {
    name: 'Crispy-Hähnchen-Wraps', slot: 'haupt', device: 'airfryer', alt: ['ofen'], time: 15, proteins: ['haehnchen', 'milch'],
    ingredients: [
      { item: 'haehnchenbrust', amount: 200, note: 'in Streifen' },
      { item: 'wraps', amount: 2, side: [1, 4, 1] },
      { item: 'tk_paprika', amount: 200 },
      { item: 'skyr', amount: 100, note: 'mit Knoblauch und Salz als Soße' },
      { item: 'oel', amount: 1 },
    ],
    steps: [
      'Hähnchenstreifen mit Öl, Paprikapulver und Salz mischen, bei 200 °C 12 Minuten in den Airfryer.',
      'Paprika-Mix für die letzten 6 Minuten dazu.',
      'Wraps mit Soße bestreichen, Hähnchen und Paprika rein, einrollen.',
    ],
  },
  haehnchen_suesskartoffel: {
    name: 'Hähnchen mit Süßkartoffel-Pommes', slot: 'haupt', device: 'airfryer', alt: ['ofen'], time: 15, proteins: ['haehnchen'],
    ingredients: [
      { item: 'haehnchenschenkel', amount: 220 },
      { item: 'suesskartoffeln', amount: 350, side: [200, 900, 50] },
      { item: 'tk_bohnen', amount: 250 },
      { item: 'oel', amount: 2 },
      { item: 'gewuerz', amount: 0, text: 'Salz, Paprika' },
    ],
    steps: [
      'Süßkartoffeln in Stifte schneiden, mit 1 TL Öl und Salz bei 200 °C etwa 20 Minuten in den Airfryer.',
      'Hähnchen mit 1 TL Öl und Gewürz einreiben und nach 5 Minuten dazulegen.',
      GEMUESE,
      DURCH,
    ],
  },
  pute_paprika_reis: {
    name: 'Puten-Paprika-Reis', slot: 'haupt', device: 'reiskocher', time: 10, proteins: ['pute'],
    ingredients: [
      { item: 'reis', amount: 90, side: [50, 250] },
      { item: 'tk_paprika', amount: 250 },
      { item: 'putenbrust', amount: 200, note: 'in Würfeln' },
      { item: 'tomaten', amount: 200 },
      { item: 'oel', amount: 1 },
      { item: 'gewuerz', amount: 0, text: 'Paprikapulver, Salz' },
    ],
    steps: [
      'Reis waschen und mit etwas weniger Wasser als sonst in den Reiskocher geben.',
      'Paprika, Pute und Tomaten obendrauf, würzen, Öl drüber, Reiskocher starten.',
      'Danach umrühren. Die Pute muss innen durch sein.',
    ],
  },
  pute_gyros: {
    name: 'Puten-Gyros mit Kartoffeln', slot: 'haupt', device: 'airfryer', alt: ['ofen'], time: 15, proteins: ['pute', 'milch'],
    ingredients: [
      { item: 'putenbrust', amount: 220, note: 'in Streifen' },
      { item: 'kartoffeln', amount: 300, side: [150, 900, 50] },
      { item: 'tk_paprika', amount: 200 },
      { item: 'skyr', amount: 100, note: 'mit Knoblauch als Tzatziki' },
      { item: 'oel', amount: 2 },
      { item: 'gewuerz', amount: 0, text: 'Gyrosgewürz' },
    ],
    steps: [KARTOFFELN, 'Pute mit 1 TL Öl und Gyrosgewürz mischen und für die letzten 12 Minuten dazu.', 'Paprika für die letzten 8 Minuten dazu.', 'Mit dem Skyr-Tzatziki essen.'],
  },
  abend_huefte: {
    name: 'Hüftsteak mit Kartoffeln', slot: 'haupt', device: 'airfryer', alt: ['ofen'], time: 15, proteins: ['rind'],
    ingredients: [
      { item: 'rinderhuefte', amount: 250 },
      { item: 'kartoffeln', amount: 350, side: [200, 900, 50] },
      { item: 'tk_bohnen', amount: 250 },
      { item: 'oel', amount: 2 },
      { item: 'gewuerz', amount: 0, text: 'Salz, Pfeffer' },
    ],
    steps: [KARTOFFELN, 'Steak mit 1 TL Öl einreiben und für die letzten 8–10 Minuten dazu, einmal wenden.', GEMUESE, 'Steak 3 Minuten ruhen lassen, dann salzen und pfeffern.'],
  },
  chili_con_carne: {
    name: 'Chili con Carne', slot: 'haupt', device: 'herd', time: 15, proteins: ['rind'],
    ingredients: [
      { item: 'rinderhack', amount: 200 },
      { item: 'kidneybohnen', amount: 150 },
      { item: 'mais', amount: 80 },
      { item: 'tomaten', amount: 250 },
      { item: 'tk_paprika', amount: 150 },
      { item: 'reis', amount: 50, side: [0, 220] },
      { item: 'gewuerz', amount: 0, text: 'Chili, Kreuzkümmel, Salz' },
    ],
    steps: [
      'Reis im Reiskocher starten.',
      'Hack im Topf ohne Öl krümelig braten.',
      'Paprika, Tomaten, Bohnen und Mais dazu, würzen, 10 Minuten köcheln.',
    ],
    tip: 'Chili schmeckt am zweiten Tag noch besser.',
  },
  hack_reis_pfanne: {
    name: 'Hack-Reis-Pfanne', slot: 'haupt', device: 'herd', time: 15, proteins: ['rind'],
    ingredients: [
      { item: 'rinderhack', amount: 180 },
      { item: 'reis', amount: 80, side: [40, 220] },
      { item: 'tk_gemuese_mix', amount: 250 },
      { item: 'sojasauce', amount: 1 },
      { item: 'oel', amount: 1 },
    ],
    steps: ['Reis im Reiskocher starten.', 'Hack in der Pfanne mit dem Öl krümelig braten, Gemüse dazu, 5 Minuten weiterbraten.', 'Reis unterheben, mit Sojasauce abschmecken.'],
  },
  burger_bowl: {
    name: 'Burger-Bowl mit Wedges', slot: 'haupt', device: 'airfryer', alt: ['ofen'], time: 15, proteins: ['rind', 'milch'],
    ingredients: [
      { item: 'rinderhack', amount: 180, note: 'zu 2 Patties geformt' },
      { item: 'kartoffeln', amount: 300, side: [150, 900, 50] },
      { item: 'rohkost', amount: 200 },
      { item: 'skyr', amount: 100, note: 'mit Senf und Gewürzgurke als Burgersoße' },
      { item: 'oel', amount: 1 },
    ],
    steps: [
      'Kartoffeln in Spalten schneiden, mit dem Öl und Salz bei 200 °C etwa 22 Minuten in den Airfryer.',
      'Patties salzen und für die letzten 10 Minuten dazu, einmal wenden.',
      'Rohkost klein schneiden, alles in eine Schüssel, Soße drüber.',
    ],
  },
  abend_schweinelachs: {
    name: 'Schweinelachs mit Kartoffeln', slot: 'haupt', device: 'airfryer', alt: ['ofen'], time: 15, proteins: ['schwein'],
    ingredients: [
      { item: 'schweinelachs', amount: 250 },
      { item: 'kartoffeln', amount: 350, side: [200, 900, 50] },
      { item: 'tk_bohnen', amount: 250 },
      { item: 'oel', amount: 2 },
      { item: 'gewuerz', amount: 0, text: 'Salz, Pfeffer, Paprika' },
    ],
    steps: [KARTOFFELN, 'Schweinelachs mit 1 TL Öl und Gewürz einreiben und für die letzten 12–15 Minuten dazu, einmal wenden.', GEMUESE],
  },
  schwein_bowl: {
    name: 'Honig-Soja-Schwein mit Reis', slot: 'haupt', device: 'reiskocher', time: 10, proteins: ['schwein'],
    ingredients: [
      { item: 'reis', amount: 90, side: [50, 250] },
      { item: 'tk_gemuese_mix', amount: 250 },
      { item: 'schweinelachs', amount: 200, note: 'in dünnen Streifen' },
      { item: 'sojasauce', amount: 2 },
      { item: 'honig', amount: 1 },
    ],
    steps: ['Fleisch mit Sojasauce und Honig mischen.', REIS, 'Gemüse und Fleisch samt Soße obendrauf, Reiskocher starten, danach umrühren.'],
  },
  lachs_reis: {
    name: 'Lachs mit Reis und Brokkoli', slot: 'haupt', device: 'reiskocher', time: 5, proteins: ['fisch', 'milch'],
    ingredients: [
      { item: 'reis', amount: 90, side: [50, 250] },
      { item: 'tk_brokkoli', amount: 250 },
      { item: 'lachs', amount: 150 },
      { item: 'skyr', amount: 100, note: 'mit Dill und Zitrone als Soße' },
      { item: 'sojasauce', amount: 1 },
    ],
    steps: [REIS, 'Brokkoli und den gefrorenen Lachs obendrauf legen, Sojasauce drüber, Reiskocher starten.', 'Mit der Skyr-Soße essen.'],
  },
  kabeljau_kartoffel: {
    name: 'Knusper-Fisch mit Kartoffeln', slot: 'haupt', device: 'airfryer', alt: ['ofen'], time: 10, proteins: ['fisch', 'milch'],
    ingredients: [
      { item: 'kabeljau', amount: 250 },
      { item: 'kartoffeln', amount: 400, side: [200, 900, 50] },
      { item: 'tk_spinat', amount: 250 },
      { item: 'skyr', amount: 100, note: 'mit Kräutern als Soße' },
      { item: 'oel', amount: 2 },
    ],
    steps: [KARTOFFELN, 'Fisch mit 1 TL Öl, Salz und Paprika einreiben, gefroren für die letzten 15 Minuten dazu.', 'Spinat in der Mikrowelle oder im Topf erhitzen, salzen.'],
  },
  thunfisch_nudeln: {
    name: 'Thunfisch-Tomaten-Nudeln', slot: 'haupt', device: 'herd', time: 15, proteins: ['fisch'],
    ingredients: [
      { item: 'nudeln', amount: 100, side: [50, 250] },
      { item: 'thunfisch', amount: 1 },
      { item: 'tomaten', amount: 250 },
      { item: 'tk_spinat', amount: 150 },
      { item: 'oel', amount: 1 },
    ],
    steps: ['Nudeln kochen.', 'Tomaten, Spinat und Öl im Topf 5 Minuten köcheln, salzen.', 'Thunfisch und Nudeln unterheben.'],
  },
  garnelen_reis: {
    name: 'Knoblauch-Garnelen-Reis', slot: 'haupt', device: 'reiskocher', time: 5, proteins: ['fisch'],
    ingredients: [
      { item: 'reis', amount: 100, side: [50, 250] },
      { item: 'tk_gemuese_mix', amount: 300 },
      { item: 'garnelen', amount: 250 },
      { item: 'sojasauce', amount: 1 },
      { item: 'oel', amount: 2 },
      { item: 'gewuerz', amount: 0, text: '2 Knoblauchzehen, gehackt' },
    ],
    steps: [REIS, 'Gemüse und gefrorene Garnelen obendrauf, Knoblauch, Sojasauce und Öl drüber.', 'Reiskocher starten, danach umrühren.'],
  },
  shakshuka: {
    name: 'Shakshuka mit Brot', slot: 'haupt', device: 'herd', time: 15, proteins: ['ei', 'milch'],
    ingredients: [
      { item: 'eier', amount: 4 },
      { item: 'tomaten', amount: 400 },
      { item: 'tk_paprika', amount: 150 },
      { item: 'huettenkaese', amount: 100 },
      { item: 'vollkornbrot', amount: 2, side: [1, 5, 1] },
      { item: 'gewuerz', amount: 0, text: 'Kreuzkümmel, Paprika, Salz' },
    ],
    steps: ['Paprika und Tomaten in der Pfanne 8 Minuten köcheln, würzen.', '4 Mulden machen, Eier hineinschlagen, Deckel drauf, 6 Minuten stocken lassen.', 'Hüttenkäse drüber, mit dem Brot essen.'],
  },
  ofenkartoffel_huettenkaese: {
    name: 'Ofenkartoffel mit Hüttenkäse', slot: 'haupt', device: 'airfryer', alt: ['ofen'], time: 10, proteins: ['milch'],
    ingredients: [
      { item: 'kartoffeln', amount: 400, side: [250, 900, 50] },
      { item: 'huettenkaese', amount: 300 },
      { item: 'tk_brokkoli', amount: 250 },
      { item: 'gewuerz', amount: 0, text: 'Salz, Pfeffer, Schnittlauch' },
    ],
    steps: ['Kartoffeln halbieren und bei 200 °C etwa 25 Minuten in den Airfryer.', GEMUESE, 'Hüttenkäse würzen und auf die heißen Kartoffeln geben.'],
  },

  // ---------- Schwäbisch, leichter gekocht ----------
  maultaschen_ei: {
    name: 'Maultaschen mit Ei und Spinat', slot: 'haupt', device: 'herd', time: 15, proteins: ['schwein', 'ei'], region: 'schwaebisch',
    ingredients: [
      { item: 'maultaschen', amount: 3, side: [2, 6, 1] },
      { item: 'eier', amount: 3 },
      { item: 'tk_spinat', amount: 250 },
      { item: 'zwiebeln', amount: 50 },
      { item: 'oel', amount: 1 },
    ],
    steps: [
      'Maultaschen in Streifen schneiden und mit der gewürfelten Zwiebel im Öl anbraten.',
      'Spinat dazugeben, bis er aufgetaut ist.',
      'Eier verquirlen, drübergießen und stocken lassen. Salzen, pfeffern.',
    ],
    tip: 'Der Klassiker „Maultaschen mit Ei“, hier mit Spinat statt viel Butter.',
  },
  linsen_spaetzle: {
    name: 'Linsen mit Spätzle und Saitenwürstle', slot: 'haupt', device: 'herd', time: 15, proteins: ['haehnchen'], region: 'schwaebisch',
    ingredients: [
      { item: 'linsen', amount: 250 },
      { item: 'tk_suppengemuese', amount: 150 },
      { item: 'spaetzle', amount: 125, side: [75, 300, 25] },
      { item: 'gefluegelwiener', amount: 100, note: 'als Saitenwürstle' },
      { item: 'bruehe', amount: 1 },
      { item: 'gewuerz', amount: 0, text: 'Essig, Senf, Pfeffer' },
    ],
    steps: [
      'Suppengemüse mit der Brühe in 100 ml Wasser 5 Minuten kochen, Linsen dazu, mit einem Schuss Essig abschmecken.',
      'Die Würstle 5 Minuten in heißem Wasser ziehen lassen, nicht kochen, sonst platzen sie.',
      'Spätzle in der Pfanne oder Mikrowelle erwärmen.',
    ],
  },
  kartoffelsalat_pute: {
    name: 'Schwäbischer Kartoffelsalat mit Putenschnitzel', slot: 'haupt', device: 'airfryer', alt: ['ofen'], time: 20, proteins: ['pute'], region: 'schwaebisch',
    ingredients: [
      { item: 'kartoffeln', amount: 350, side: [200, 900, 50] },
      { item: 'putenbrust', amount: 220, note: 'als dünne Schnitzel' },
      { item: 'rohkost', amount: 200, note: 'Gurke und Feldsalat' },
      { item: 'zwiebeln', amount: 50 },
      { item: 'bruehe', amount: 1 },
      { item: 'oel', amount: 2 },
      { item: 'gewuerz', amount: 0, text: 'Essig, Senf, Salz, Pfeffer' },
    ],
    steps: [
      'Kartoffeln im Reiskocher oder Topf garen, pellen und in dünne Scheiben schneiden.',
      'Zwiebel fein hacken, mit 100 ml heißer Brühe, Essig, Senf und Öl verrühren und über die warmen Kartoffeln gießen. 10 Minuten ziehen lassen, dann wird er schön schlonzig.',
      'Schnitzel salzen und pfeffern, bei 200 °C 8–10 Minuten in den Airfryer, einmal wenden.',
      'Gurke und Feldsalat dazu.',
    ],
  },
  gaisburger_marsch: {
    name: 'Schneller Gaisburger Marsch', slot: 'haupt', device: 'herd', time: 20, proteins: ['rind'], region: 'schwaebisch',
    ingredients: [
      { item: 'rinderhuefte', amount: 200, note: 'in dünnen Streifen' },
      { item: 'kartoffeln', amount: 250, side: [100, 700, 50] },
      { item: 'spaetzle', amount: 60 },
      { item: 'tk_suppengemuese', amount: 250 },
      { item: 'zwiebeln', amount: 50 },
      { item: 'bruehe', amount: 2 },
    ],
    steps: [
      'Kartoffeln würfeln und mit Suppengemüse und Brühe in 600 ml Wasser 12 Minuten kochen.',
      'Fleischstreifen und Spätzle dazu und 3 Minuten ziehen lassen.',
      'Zwiebel in Ringen ohne Fett in der Pfanne bräunen und obendrauf geben.',
    ],
    tip: 'Das Original köchelt stundenlang mit Suppenfleisch. Mit dünnen Hüftstreifen geht es in 20 Minuten.',
  },
  zwiebelrostbraten: {
    name: 'Zwiebelrostbraten mit Spätzle', slot: 'haupt', device: 'herd', time: 20, proteins: ['rind'], region: 'schwaebisch',
    ingredients: [
      { item: 'rinderhuefte', amount: 200 },
      { item: 'spaetzle', amount: 150, side: [75, 300, 25] },
      { item: 'zwiebeln', amount: 150 },
      { item: 'tk_bohnen', amount: 250 },
      { item: 'oel', amount: 2 },
      { item: 'gewuerz', amount: 0, text: 'Senf, Salz, Pfeffer' },
    ],
    steps: [
      'Zwiebeln in Ringen mit 1 TL Öl langsam goldbraun braten und herausnehmen.',
      'Steak dünn mit Senf bestreichen und im restlichen Öl 2–3 Minuten pro Seite braten.',
      'Spätzle und Bohnen in der Pfanne erwärmen, die Zwiebeln aufs Fleisch.',
    ],
  },
  kaesespaetzle_light: {
    name: 'Käsespätzle, leichter', slot: 'haupt', device: 'herd', time: 15, proteins: ['milch'], region: 'schwaebisch',
    ingredients: [
      { item: 'spaetzle', amount: 200, side: [100, 350, 25] },
      { item: 'kaese_light', amount: 60, note: 'gerieben' },
      { item: 'skyr', amount: 100 },
      { item: 'zwiebeln', amount: 100 },
      { item: 'rohkost', amount: 200, note: 'grüner Salat dazu' },
      { item: 'oel', amount: 1 },
    ],
    steps: [
      'Zwiebeln in Ringen mit dem Öl goldbraun braten.',
      'Spätzle in der Pfanne erwärmen, Skyr und Käse unterrühren, bis alles schmilzt. Salzen, pfeffern.',
      'Zwiebeln obendrauf, Salat dazu.',
    ],
    tip: 'Skyr statt Sahne und leichter Käse sparen gut die Hälfte der Kalorien.',
  },
  schupfnudeln_sauerkraut: {
    name: 'Schupfnudeln mit Sauerkraut und Kasseler', slot: 'haupt', device: 'herd', time: 15, proteins: ['schwein'], region: 'schwaebisch',
    ingredients: [
      { item: 'schupfnudeln', amount: 200, side: [100, 400, 25] },
      { item: 'sauerkraut', amount: 250 },
      { item: 'kasseler', amount: 200, note: 'in Würfeln' },
      { item: 'zwiebeln', amount: 50 },
      { item: 'oel', amount: 1 },
    ],
    steps: [
      'Kasseler und Zwiebel im Öl anbraten.',
      'Schupfnudeln dazu und goldbraun braten.',
      'Sauerkraut unterheben und 5 Minuten mitbraten.',
    ],
  },
  frei: {
    name: 'Freier Abend', slot: 'haupt', device: 'frei', time: 0, proteins: [],
    fixed: { kcal: 1000, protein: 30, fat: 45, carbs: 100, fiber: 5, veg: 0 },
    ingredients: [],
    steps: ['Burger oder Pizza, ganz ohne schlechtes Gewissen.', 'Dafür gibt es heute keinen Snack.'],
    tip: 'Die Nährwerte sind eine grobe Schätzung.',
  },

  // ---------- Snacks ----------
  snack_nuesse: {
    name: 'Nüsse und Banane', slot: 'snack', device: 'ohne', time: 1, proteins: [],
    ingredients: [{ item: 'nuesse', amount: 30 }, { item: 'banane', amount: 1 }],
    steps: ['Die Nüsse abwiegen statt aus der Tüte zu essen. 30 g sind schnell überschritten.'],
  },
  snack_shake: {
    name: 'Eiweiß-Shake', slot: 'snack', device: 'ohne', time: 1, proteins: ['milch'],
    ingredients: [{ item: 'whey', amount: 30 }, { item: 'milch', amount: 300 }],
    steps: ['Whey mit der Milch im Shaker schütteln.'],
  },
  skyr_beeren: {
    name: 'Skyr mit Beeren', slot: 'snack', device: 'ohne', time: 2, proteins: ['milch'],
    ingredients: [{ item: 'skyr', amount: 250 }, { item: 'tk_beeren', amount: 100 }],
    steps: ['Beeren am Vorabend in den Kühlschrank legen oder kurz in der Mikrowelle antauen.'],
  },
  protein_pudding: {
    name: 'Protein-Pudding', slot: 'snack', device: 'ohne', time: 0, proteins: ['milch'],
    ingredients: [{ item: 'proteinpudding', amount: 1 }],
    steps: ['Deckel auf, Löffel rein.'],
  },
  reiswaffeln_erdnuss: {
    name: 'Reiswaffeln mit Erdnussbutter', slot: 'snack', device: 'ohne', time: 2, proteins: [],
    ingredients: [{ item: 'reiswaffeln', amount: 3 }, { item: 'erdnussbutter', amount: 1 }],
    steps: ['Erdnussbutter dünn auf die Reiswaffeln streichen.'],
  },
  huettenkaese_rohkost: {
    name: 'Hüttenkäse mit Rohkost', slot: 'snack', device: 'ohne', time: 3, proteins: ['milch'],
    ingredients: [{ item: 'huettenkaese', amount: 200 }, { item: 'rohkost', amount: 200 }],
    steps: ['Rohkost in Sticks schneiden und in den Hüttenkäse dippen.'],
  },
  quark_apfel: {
    name: 'Zimt-Quark mit Apfel', slot: 'snack', device: 'ohne', time: 3, proteins: ['milch'],
    ingredients: [{ item: 'magerquark', amount: 250 }, { item: 'apfel', amount: 1 }, { item: 'gewuerz', amount: 0, text: 'Zimt' }],
    steps: ['Apfel klein schneiden, mit Zimt unter den Quark rühren.'],
  },
  eier_airfryer: {
    name: 'Eier aus dem Airfryer mit Rohkost', slot: 'snack', device: 'airfryer', time: 2, proteins: ['ei'],
    ingredients: [{ item: 'eier', amount: 2 }, { item: 'rohkost', amount: 150 }],
    steps: ['Eier bei 150 °C 15 Minuten in den Airfryer, dann kalt abschrecken.', 'Mit Salz und Rohkost essen.'],
    tip: 'Gleich 6 Eier machen, sie halten im Kühlschrank eine Woche.',
  },

  // ---------- Virale Rezepte von Instagram und TikTok ----------
  pesto_eier: {
    name: 'Pesto-Eier auf Sauerteigbrot mit Hüttenkäse', slot: 'fruehstueck', device: 'herd', time: 7, proteins: ['ei', 'milch'], viral: true,
    ingredients: [
      { item: 'eier', amount: 3 },
      { item: 'pesto', amount: 1 },
      { item: 'sauerteigbrot', amount: 1, side: [0, 3, 1] },
      { item: 'huettenkaese', amount: 50 },
      { item: 'honig', amount: 1 },
      { item: 'gewuerz', amount: 0, text: 'Chiliflocken, Salz, Pfeffer' },
    ],
    steps: [
      'Pesto in einer beschichteten Pfanne bei mittlerer Hitze verteilen, bis es brutzelt.',
      'Eier direkt ins Pesto schlagen, salzen und mit Deckel 3–4 Minuten braten, bis das Eiweiß fest ist.',
      'Brot toasten, mit Hüttenkäse bestreichen, die Eier darauflegen, mit Honig beträufeln und Chiliflocken drüberstreuen.',
    ],
    tip: 'Das Pesto ersetzt das Bratöl: Es brät am Rand knusprig und würzt die Eier gleich mit.',
  },
  tortilla_faltwrap: {
    name: 'Tortilla-Faltwrap mit Ei und Putenschinken', slot: 'fruehstueck', device: 'herd', time: 10, proteins: ['ei', 'pute', 'milch'], viral: true,
    ingredients: [
      { item: 'wraps', amount: 1, side: [1, 2, 1] },
      { item: 'eier', amount: 2 },
      { item: 'putenaufschnitt', amount: 40, note: 'Putenschinken' },
      { item: 'kaese_light', amount: 20 },
      { item: 'rohkost', amount: 50, note: 'Tomate in Scheiben' },
      { item: 'gewuerz', amount: 0, text: 'Salz, Pfeffer, Schnittlauch' },
    ],
    steps: [
      'Eier verquirlen, salzen und in einer beschichteten Pfanne ohne Fett zu Rührei stocken lassen, dann herausnehmen.',
      'Den Wrap von der Mitte bis zum Rand einmal einschneiden und die vier Viertel belegen: Rührei, Putenschinken, Käse, Tomate.',
      'Beim Schnitt anfangen und Viertel für Viertel zu einem Dreieck falten.',
      'In der Pfanne von jeder Seite 2 Minuten goldbraun rösten, bis der Käse schmilzt.',
    ],
    tip: 'Leg den Käse in eins der mittleren Viertel: Beim Rösten schmilzt er und klebt die Lagen zusammen, so fällt nichts heraus.',
  },
  huettenkaese_pancakes: {
    name: 'Hüttenkäse-Hafer-Pancakes mit Beeren', slot: 'fruehstueck', device: 'herd', time: 12, proteins: ['milch', 'ei'], viral: true,
    ingredients: [
      { item: 'haferflocken', amount: 40, side: [20, 100] },
      { item: 'huettenkaese', amount: 125 },
      { item: 'eier', amount: 2 },
      { item: 'tk_beeren', amount: 80 },
      { item: 'oel', amount: 1 },
      { item: 'gewuerz', amount: 0, text: '½ TL Backpulver, Zimt, Prise Salz' },
    ],
    steps: [
      'Haferflocken, Hüttenkäse, Eier, Backpulver, Zimt und Salz mit dem Pürierstab glatt mixen und 5 Minuten quellen lassen.',
      'Öl in einer beschichteten Pfanne verteilen, kleine Pancakes hineingeben und bei mittlerer Hitze etwa 2 Minuten pro Seite backen.',
      'Zum Schluss die Beeren kurz in der Pfanne warm werden lassen und über die Pancakes geben.',
    ],
    tip: 'Mix den Teig richtig glatt: Dann schmeckt niemand den Hüttenkäse heraus und die Pancakes werden fluffig statt krümelig.',
  },
  skyr_bagel_lachs: {
    name: 'Skyr-Bagel mit Räucherlachs', slot: 'fruehstueck', device: 'airfryer', alt: ['ofen'], time: 10, proteins: ['milch', 'fisch'], viral: true,
    ingredients: [
      { item: 'weizenmehl', amount: 70, side: [50, 120] },
      { item: 'skyr', amount: 80 },
      { item: 'frischkaese_light', amount: 30 },
      { item: 'raeucherlachs', amount: 50 },
      { item: 'rohkost', amount: 50, note: 'Gurke in Scheiben' },
      { item: 'gewuerz', amount: 0, text: '1 TL Backpulver, Salz, Sesam, Dill' },
    ],
    steps: [
      'Mehl, Backpulver und eine Prise Salz mit dem Skyr zu einem glatten, weichen Teig verkneten. Klebt er, kommt etwas Mehl dazu, bröselt er, 1–2 EL Wasser.',
      'Teig halbieren, zu zwei Rollen formen und zu Ringen schließen. Mit etwas Wasser bestreichen und in Sesam drücken.',
      'Bei 160 °C etwa 15 Minuten in den Airfryer (Ofen: 190 °C, 20 Minuten), bis sie goldbraun sind.',
      'Abkühlen lassen, aufschneiden und mit Frischkäse, Lachs, Gurke und Dill belegen.',
    ],
    tip: 'Lass die Bagels erst abkühlen, bevor du sie aufschneidest: Warm sind sie innen noch klebrig.',
  },
  baked_oats: {
    name: 'Baked Oats mit Skyr und Whey', slot: 'fruehstueck', device: 'airfryer', alt: ['ofen'], time: 5, proteins: ['milch', 'ei'], viral: true,
    ingredients: [
      { item: 'haferflocken', amount: 50, side: [30, 110] },
      { item: 'eier', amount: 1 },
      { item: 'banane', amount: 0.5 },
      { item: 'skyr', amount: 100 },
      { item: 'whey', amount: 15 },
      { item: 'tk_beeren', amount: 50 },
      { item: 'gewuerz', amount: 0, text: '1 TL Backpulver, Zimt' },
    ],
    steps: [
      'Haferflocken, Ei, Banane, Skyr, Whey, Backpulver und Zimt mit dem Pürierstab glatt mixen.',
      'In eine kleine ofenfeste Form füllen und die gefrorenen Beeren hineindrücken.',
      'Bei 170 °C etwa 15 Minuten in den Airfryer (Ofen: 180 °C, 25 Minuten), bis die Mitte nicht mehr feucht glänzt.',
    ],
    tip: 'Die Haferflocken wirklich fein mixen: Erst dann wird es luftig wie Kuchen statt wie warmes Müsli.',
  },
  joghurt_toast: {
    name: 'Joghurt-Toast mit Beeren', slot: 'fruehstueck', device: 'airfryer', alt: ['ofen'], time: 5, proteins: ['milch', 'ei'], viral: true,
    ingredients: [
      { item: 'sauerteigbrot', amount: 2, side: [1, 3, 1] },
      { item: 'skyr', amount: 150 },
      { item: 'eier', amount: 1 },
      { item: 'honig', amount: 1 },
      { item: 'tk_beeren', amount: 100 },
      { item: 'gewuerz', amount: 0, text: 'Zimt' },
    ],
    steps: [
      'Skyr, Ei, Honig und Zimt glatt verrühren.',
      'Mit dem Löffelrücken in jede Brotscheibe eine tiefe Mulde drücken, die Creme hineinstreichen und die gefrorenen Beeren darauf verteilen. Was nicht aufs Brot passt, kommt in eine kleine ofenfeste Tasse und backt mit.',
      'Bei 180 °C etwa 8 Minuten in den Airfryer (Ofen: 200 °C, 12 Minuten), bis die Creme fest ist wie Pudding.',
    ],
    tip: 'Drück die Mulde fest ein und lass rundum einen Rand stehen, sonst läuft die Creme beim Backen herunter.',
  },
  feta_spiegeleier: {
    name: 'Feta-Spiegeleier auf Vollkornbrot', slot: 'fruehstueck', device: 'herd', time: 6, proteins: ['ei', 'milch'], viral: true,
    ingredients: [
      { item: 'eier', amount: 3 },
      { item: 'feta_light', amount: 30, note: 'zerbröselt' },
      { item: 'vollkornbrot', amount: 1, side: [0, 3, 1] },
      { item: 'rohkost', amount: 100, note: 'Tomaten' },
      { item: 'gewuerz', amount: 0, text: 'Chiliflocken, Oregano, Pfeffer' },
    ],
    steps: [
      'Feta in einer beschichteten Pfanne zu einem Ring zerbröseln und bei mittlerer Hitze 1–2 Minuten brutzeln lassen.',
      'Eier in die Mitte schlagen, Deckel drauf und etwa 3 Minuten braten, bis das Eiweiß fest ist.',
      'Samt Feta-Kruste aufs Brot heben, mit Chiliflocken und Oregano bestreuen. Tomaten dazu.',
    ],
    tip: 'Lass den Feta allein brutzeln, bis der Rand bräunt, bevor die Eier drauf kommen, und salz nicht nach, der Feta würzt genug.',
  },
  wolkeneier: {
    name: 'Wolkeneier mit Parmesan', slot: 'fruehstueck', device: 'ofen', alt: ['airfryer'], time: 10, proteins: ['ei', 'milch'], viral: true,
    ingredients: [
      { item: 'eier', amount: 3 },
      { item: 'parmesan', amount: 20, note: 'fein gerieben' },
      { item: 'vollkornbrot', amount: 1, side: [0, 3, 1] },
      { item: 'gewuerz', amount: 0, text: 'Schnittlauch, Salz, Pfeffer' },
    ],
    steps: [
      'Eier trennen, die Eigelbe einzeln in den Schalenhälften lassen. Eiweiß mit einer Prise Salz steif schlagen, Parmesan und Schnittlauch unterheben.',
      'Drei Wolken aufs Backpapier setzen und in jede eine Mulde drücken. Bei 230 °C 3 Minuten in den Ofen (Airfryer: 170 °C, 4 Minuten).',
      'Je ein Eigelb in die Mulde gleiten lassen und noch 3 Minuten backen, bis die Spitzen goldbraun sind. Mit dem Brot essen.',
    ],
    tip: 'Trenn jedes Ei einzeln über einer Tasse: Schon ein Hauch Eigelb im Eiweiß, und es wird nicht steif.',
  },
  dampfei: {
    name: 'Koreanisches Dampfei mit Vollkornbrot', slot: 'fruehstueck', device: 'herd', time: 8, proteins: ['ei'], viral: true,
    ingredients: [
      { item: 'eier', amount: 4 },
      { item: 'bruehe', amount: 1 },
      { item: 'vollkornbrot', amount: 1, side: [0, 3, 1] },
      { item: 'gewuerz', amount: 0, text: 'Frühlingszwiebel, ein paar Tropfen Sesamöl, Salz' },
    ],
    steps: [
      '200 ml Wasser mit der Brühe in einem kleinen Topf aufkochen, die Eier gut verquirlen.',
      'Eier hineingießen und bei mittlerer Hitze etwa 1 Minute rühren, bis sie halb gestockt sind wie weiches Rührei.',
      'Frühlingszwiebel drüberstreuen, Deckel drauf und bei kleinster Hitze 3–4 Minuten stocken lassen, bis das Ei aufgeht.',
      'Mit ein paar Tropfen Sesamöl beträufeln und mit dem Brot essen.',
    ],
    tip: 'Erst kräftig rühren, dann Deckel drauf und nur noch kleinste Hitze: So wird es fluffig wie ein Soufflé statt gummiartig und brennt unten nicht an.',
  },
  crispy_eggs: {
    name: 'Crispy Eggs mit Vollkornbrot', slot: 'fruehstueck', device: 'herd', time: 10, proteins: ['ei', 'milch'], viral: true,
    ingredients: [
      { item: 'eier', amount: 3 },
      { item: 'kaese_light', amount: 30, note: 'z. B. Gouda' },
      { item: 'vollkornbrot', amount: 1, side: [0, 3, 1] },
      { item: 'rohkost', amount: 100 },
      { item: 'gewuerz', amount: 0, text: 'Pfeffer, Paprikapulver, Schnittlauch' },
    ],
    steps: [
      'Eier 9 Minuten kochen, kalt abschrecken, pellen und längs halbieren.',
      'Käse in einer beschichteten Pfanne zu sechs kleinen Häufchen streuen und je eine Eihälfte mit der Schnittfläche nach unten daraufsetzen.',
      'Ohne Öl bei mittlerer Hitze 3–4 Minuten braten, bis der Käse goldbraun und knusprig ist.',
      'Mit Pfeffer, Paprika und Schnittlauch bestreuen, Brot und Rohkost dazu.',
    ],
    tip: 'Den Käse erst lösen, wenn er am Rand richtig braun ist: Dann ist er knusprig und hebt sich fast von selbst vom Pfannenboden.',
  },
  frambled_eggs: {
    name: 'Frambled Eggs auf Sauerteigbrot', slot: 'fruehstueck', device: 'herd', time: 6, proteins: ['ei', 'milch'], viral: true,
    ingredients: [
      { item: 'eier', amount: 3 },
      { item: 'sauerteigbrot', amount: 1, side: [0, 3, 1] },
      { item: 'huettenkaese', amount: 100 },
      { item: 'oel', amount: 1 },
      { item: 'gewuerz', amount: 0, text: 'Salz, Pfeffer, Schnittlauch, Chiliflocken' },
    ],
    steps: [
      'Öl in einer Pfanne richtig heiß werden lassen und die Eier hineinschlagen.',
      'Sobald das Eiweiß am Rand knusprig wird, die Eigelbe aufstechen und nur zwei-, dreimal grob durchschieben, nicht verrühren.',
      'Nach etwa 1 Minute vom Herd nehmen, salzen und pfeffern. Brot toasten, mit Hüttenkäse bestreichen und die Eier daraufgeben.',
    ],
    tip: 'Frambled heißt fried plus scrambled: Heiße Pfanne und erst schieben, wenn das Eiweiß stockt, dann bekommst du knusprige Spiegeleiränder und cremiges Rührei in einem.',
  },
  hot_honey_bowl: {
    name: 'Hot-Honey-Hack-Bowl mit Süßkartoffel und Hüttenkäse', slot: 'haupt', device: 'airfryer', alt: ['ofen'], time: 15, proteins: ['rind', 'milch'], viral: true,
    ingredients: [
      { item: 'suesskartoffeln', amount: 270, side: [100, 700, 50], note: 'in 2-cm-Würfeln' },
      { item: 'tk_brokkoli', amount: 200 },
      { item: 'rinderhack', amount: 170 },
      { item: 'huettenkaese', amount: 150 },
      { item: 'honig', amount: 2, note: 'mit Chiliflocken als Hot Honey' },
      { item: 'oel', amount: 1 },
      { item: 'gewuerz', amount: 0, text: 'Chiliflocken, Paprikapulver, Knoblauchpulver, Salz, Frühlingszwiebel' },
    ],
    steps: [
      'Süßkartoffelwürfel mit dem Öl und Salz mischen und bei 200 °C etwa 18 Minuten in den Airfryer, einmal schütteln. Den TK-Brokkoli für die letzten 10 Minuten dazugeben.',
      'Hack mit Paprika- und Knoblauchpulver in der Pfanne ohne Öl krümelig braten, bis nichts mehr rosa ist.',
      'Hack herausnehmen, Honig und eine kräftige Prise Chiliflocken in der warmen Pfanne kurz verrühren.',
      'Süßkartoffeln, Brokkoli, Hack und Hüttenkäse nebeneinander in die Schüssel, Hot Honey drüberträufeln, Frühlingszwiebel drauf.',
    ],
    tip: 'Hot Honey musst du nicht kaufen: Honig mit Chiliflocken kurz in der noch warmen Pfanne erwärmen, dann zieht die Schärfe in den Honig.',
  },
  tuerkische_nudeln: {
    name: 'Türkische Nudeln mit Hack und Knoblauch-Skyr', slot: 'haupt', device: 'herd', time: 15, proteins: ['rind', 'milch'], viral: true,
    ingredients: [
      { item: 'nudeln', amount: 80, side: [40, 180] },
      { item: 'rinderhack', amount: 160 },
      { item: 'zwiebeln', amount: 50, note: 'fein gewürfelt' },
      { item: 'skyr', amount: 150, note: 'mit Knoblauch und Salz verrührt' },
      { item: 'oel', amount: 2, note: 'mit Paprikapulver und Chiliflocken als Paprika-Öl' },
      { item: 'gewuerz', amount: 0, text: '1 EL Tomatenmark, Paprikapulver, Chiliflocken, Knoblauch, Petersilie, Salz' },
      { item: 'rohkost', amount: 150, note: 'Gurke und Tomate als Salat' },
    ],
    steps: [
      'Nudeln in Salzwasser kochen.',
      'Hack mit der Zwiebel in der Pfanne ohne Öl krümelig und knusprig braten, bis nichts mehr rosa ist, dann Tomatenmark und Paprikapulver kurz mitrösten.',
      'Skyr mit gepresstem Knoblauch und Salz verrühren. Öl in einem kleinen Topf warm machen, vom Herd nehmen, Paprikapulver und Chiliflocken einrühren.',
      'Knoblauch-Skyr auf den Teller streichen, Nudeln und Hack drauf, Paprika-Öl drüberträufeln. Gurken-Tomaten-Salat dazu.',
    ],
    tip: 'Wie im Original kommt der Knoblauch-Skyr zuerst auf den Teller und das Paprika-Öl ganz zum Schluss drüber, so hat jede Gabel kalt, warm und scharf zugleich.',
  },
  bigmac_tacos: {
    name: 'Big-Mac-Smash-Tacos', slot: 'haupt', device: 'herd', time: 15, proteins: ['rind', 'milch'], viral: true,
    ingredients: [
      { item: 'wraps', amount: 2, side: [1, 4, 1] },
      { item: 'rinderhack', amount: 160, note: 'zu 2 Kugeln geformt' },
      { item: 'kaese_light', amount: 20 },
      { item: 'skyr', amount: 80, note: 'mit Ketchup, Senf, gehackter Gewürzgurke und Paprikapulver als Big-Mac-Soße' },
      { item: 'roemersalat', amount: 100, note: 'in feinen Streifen' },
      { item: 'zwiebeln', amount: 20, note: 'sehr fein gewürfelt' },
      { item: 'gewuerz', amount: 0, text: '1 TL Ketchup, Senf, 2 Gewürzgurken, Paprikapulver, Zwiebelpulver, Salz, Pfeffer' },
      { item: 'rohkost', amount: 100, note: 'Gurke und Tomate als Salat dazu' },
    ],
    steps: [
      'Skyr mit Ketchup, Senf, einer fein gehackten Gewürzgurke, Paprika- und Zwiebelpulver zur Soße verrühren. Je eine Hackkugel mit einem Löffel hauchdünn auf einen Wrap drücken und salzen.',
      'Wrap mit der Fleischseite nach unten in die heiße Pfanne ohne Öl legen und 3–4 Minuten braten, bis das Hack knusprig und ganz durch ist.',
      'Wenden, Käse aufs Fleisch streuen und 1 Minute weiterbraten.',
      'Mit Salat, Zwiebeln, Scheiben von der zweiten Gurke und Soße belegen und zusammenklappen.',
    ],
    tip: 'Das rohe Hack direkt auf den Wrap drücken und mit dieser Seite nach unten braten, so backt es am Wrap fest und bekommt die knusprige Smash-Burger-Kruste.',
  },
  lasagne_suppe: {
    name: 'Lasagne-Suppe leicht', slot: 'haupt', device: 'herd', time: 15, proteins: ['rind', 'milch'], viral: true,
    ingredients: [
      { item: 'rinderhack', amount: 150 },
      { item: 'zwiebeln', amount: 50, note: 'gewürfelt' },
      { item: 'tomaten', amount: 400 },
      { item: 'bruehe', amount: 1 },
      { item: 'nudeln', amount: 60, side: [20, 150], note: 'am besten Lasagneplatten, in Stücke gebrochen' },
      { item: 'huettenkaese', amount: 80 },
      { item: 'parmesan', amount: 15 },
      { item: 'gewuerz', amount: 0, text: '1 EL Tomatenmark, Knoblauch, Oregano, Basilikum, Salz, Pfeffer' },
    ],
    steps: [
      'Hack mit der Zwiebel im Topf ohne Öl krümelig braten, bis nichts mehr rosa ist, Tomatenmark und Knoblauch kurz mitrösten.',
      'Tomaten, 500 ml Wasser, Brühe und Oregano dazu und aufkochen.',
      'Lasagneplatten in Stücke brechen, dazugeben und etwa 12 Minuten köcheln, ab und zu umrühren.',
      'Hüttenkäse mit Parmesan und Pfeffer verrühren und als Klecks auf die heiße Suppe setzen, Basilikum drüber.',
    ],
    tip: 'Der Käse-Klecks kommt kalt obendrauf und wird erst beim Essen untergerührt, genau das macht aus Tomatensuppe den Lasagne-Geschmack des Originals.',
  },
  marry_me_chicken: {
    name: 'Marry-Me-Chicken leicht mit Reis', slot: 'haupt', device: 'herd', time: 20, proteins: ['haehnchen', 'milch'], viral: true,
    ingredients: [
      { item: 'reis', amount: 75, side: [40, 180] },
      { item: 'haehnchenbrust', amount: 200, note: 'quer halbiert' },
      { item: 'oel', amount: 1, note: 'gern aus dem Tomatenglas' },
      { item: 'getrocknete_tomaten', amount: 25, note: 'klein geschnitten' },
      { item: 'kochcreme', amount: 100 },
      { item: 'bruehe', amount: 1 },
      { item: 'parmesan', amount: 15 },
      { item: 'tk_spinat', amount: 200 },
      { item: 'gewuerz', amount: 0, text: 'Knoblauch, Oregano, Thymian, Chiliflocken, Paprikapulver, Salz' },
    ],
    steps: [
      'Reis waschen und mit so viel Wasser wie immer in den Reiskocher geben.',
      'Hähnchen mit Paprika und Salz würzen, im Öl je Seite 5–6 Minuten braten, bis innen nichts mehr rosa ist, und herausnehmen.',
      'Tomaten und Knoblauch in derselben Pfanne kurz anbraten, 100 ml Wasser, Brühe, Kochcreme, Kräuter, Chiliflocken und den gefrorenen Spinat dazu, Parmesan einrühren und 5 Minuten köcheln.',
      'Hähnchen zurück in die Soße legen und mit dem Reis essen.',
    ],
    tip: 'Die Soße in derselben Pfanne ansetzen, in der das Hähnchen gebraten hat, denn die Brühe löst den Bratensatz vom Boden und bringt den typischen Geschmack.',
  },
  alfredo_huettenkaese: {
    name: 'Hüttenkäse-Alfredo mit Hähnchen und Brokkoli', slot: 'haupt', device: 'herd', time: 15, proteins: ['haehnchen', 'milch'], viral: true,
    ingredients: [
      { item: 'nudeln', amount: 75, side: [40, 170], note: 'am besten Bandnudeln' },
      { item: 'haehnchenbrust', amount: 150, note: 'in Streifen' },
      { item: 'tk_brokkoli', amount: 200 },
      { item: 'huettenkaese', amount: 150 },
      { item: 'parmesan', amount: 20 },
      { item: 'oel', amount: 1 },
      { item: 'gewuerz', amount: 0, text: 'Knoblauch, Muskat, Pfeffer, Salz' },
    ],
    steps: [
      'Nudeln in Salzwasser kochen, den Brokkoli für die letzten 4 Minuten mit in den Topf. Eine Tasse Nudelwasser aufheben.',
      'Hähnchenstreifen im Öl 6–8 Minuten braten, bis innen nichts mehr rosa ist.',
      'Hüttenkäse, Parmesan, Knoblauch und einen Schuss Nudelwasser mit dem Pürierstab ganz glatt mixen.',
      'Nudeln, Brokkoli und Soße zum Hähnchen in die Pfanne geben und bei kleiner Hitze nur warm werden lassen.',
    ],
    tip: 'Die Soße nur erwärmen und nicht kochen lassen, sonst flockt der Hüttenkäse wieder aus, und ein Schuss Nudelwasser macht sie seidig wie echte Alfredo-Soße.',
  },
  tomaten_reis_haehnchen: {
    name: 'Tomaten-Hähnchen-Reis aus dem Reiskocher', slot: 'haupt', device: 'reiskocher', time: 10, proteins: ['haehnchen'], viral: true,
    ingredients: [
      { item: 'reis', amount: 80, side: [40, 190] },
      { item: 'haehnchenbrust', amount: 200, note: 'in 2-cm-Würfeln' },
      { item: 'tomaten_frisch', amount: 120, note: 'groß, Strunk keilförmig herausgeschnitten' },
      { item: 'tk_gemuese_mix', amount: 200, note: 'am besten Erbsen, Mais und Möhren' },
      { item: 'sojasauce', amount: 2 },
      { item: 'oel', amount: 1, note: 'am besten Sesamöl' },
      { item: 'gewuerz', amount: 0, text: 'Knoblauch, Pfeffer, Salz, Frühlingszwiebel' },
    ],
    steps: [
      'Reis waschen und mit etwas weniger Wasser als sonst in den Reiskocher geben, die Tomate gibt noch Saft ab.',
      'Gemüse gefroren und die gesalzenen Hähnchenwürfel obendrauf, Sojasauce und Öl drüber, die ganze Tomate in die Mitte setzen und den Reiskocher starten.',
      'Danach die Tomate mit dem Löffel zerdrücken und alles durchrühren. Das größte Hähnchenstück aufschneiden: Innen darf nichts mehr rosa sein.',
    ],
    tip: 'Den Strunk vorher keilförmig herausschneiden, dann zerfällt die Tomate nach dem Kochen fast von selbst und färbt den ganzen Reis.',
  },
  caesar_pizza: {
    name: 'Caesar-Salat-Pizza mit Hähnchenboden', slot: 'haupt', device: 'ofen', alt: ['airfryer'], time: 15, proteins: ['pute', 'ei', 'milch'], viral: true,
    ingredients: [
      { item: 'putenhack', amount: 200 },
      { item: 'eier', amount: 1 },
      { item: 'kaese_light', amount: 30 },
      { item: 'parmesan', amount: 20, note: 'halb in den Boden, halb obendrauf' },
      { item: 'roemersalat', amount: 220, note: 'in Streifen' },
      { item: 'skyr', amount: 60, note: 'mit Zitronensaft, Senf, Knoblauch, Worcestersauce und Pfeffer als Caesar-Dressing' },
      { item: 'vollkornbrot', amount: 2, side: [0, 5, 1], note: 'in Würfeln als Croutons' },
      { item: 'gewuerz', amount: 0, text: 'Zitronensaft, Senf, Knoblauch, 1 Spritzer Worcestersauce, italienische Kräuter, Salz, Pfeffer' },
    ],
    steps: [
      'Hähnchenhack, Ei, Reibekäse, die Hälfte vom Parmesan, Kräuter und Salz verkneten und zwischen zwei Backpapieren zu einem dünnen Kreis drücken.',
      'Oberes Papier abziehen und den Boden bei 200 °C Umluft etwa 20 Minuten backen, bis er goldbraun und innen ganz durch ist. Die Brotwürfel kommen für die letzten 6 Minuten mit aufs Blech.',
      'Skyr mit Zitronensaft, Senf, Knoblauch, Worcestersauce und Pfeffer verrühren und den Salat darin wenden.',
      'Salat auf den heißen Boden häufen, Croutons und restlichen Parmesan drüber und wie eine Pizza schneiden.',
    ],
    tip: 'Den Boden zwischen zwei Backpapieren richtig dünn drücken, sonst bleibt er in der Mitte weich statt knusprig.',
  },
  feta_pasta: {
    name: 'Ofen-Feta-Pasta mit Hähnchen', slot: 'haupt', device: 'ofen', alt: ['airfryer'], time: 10, proteins: ['haehnchen', 'milch'], viral: true,
    ingredients: [
      { item: 'nudeln', amount: 90, side: [50, 190] },
      { item: 'haehnchenbrust', amount: 150, note: 'in 2-cm-Würfeln' },
      { item: 'feta_light', amount: 50, note: 'am Stück' },
      { item: 'kirschtomaten', amount: 250 },
      { item: 'oel', amount: 1 },
      { item: 'gewuerz', amount: 0, text: 'Knoblauch, Chiliflocken, Basilikum, Salz, Pfeffer' },
    ],
    steps: [
      'Kirschtomaten, Hähnchenwürfel, Knoblauch, Öl, Chili und Salz in eine kleine Auflaufform geben, den Feta als Block in die Mitte legen.',
      'Bei 200 °C Umluft etwa 25 Minuten backen, bis die Tomaten platzen und das Hähnchen innen nicht mehr rosa ist.',
      'In der Zeit die Nudeln kochen und eine halbe Tasse Nudelwasser aufheben.',
      'Feta und Tomaten mit der Gabel zerdrücken, Nudeln und einen Schuss Nudelwasser unterrühren, Basilikum drüber.',
    ],
    tip: 'Den Feta im Ganzen backen und erst in der Form zerdrücken, so schmilzt er mit dem Tomatensaft zu einer cremigen Soße.',
  },
  bohnensalat_haehnchen: {
    name: 'Dichter Bohnensalat mit Hähnchen', slot: 'haupt', device: 'ohne', time: 15, proteins: ['haehnchen', 'milch'], viral: true,
    ingredients: [
      { item: 'kidneybohnen', amount: 200, side: [100, 500, 50] },
      { item: 'haehnchen_gegart', amount: 180 },
      { item: 'mais', amount: 80 },
      { item: 'rohkost', amount: 200, note: 'Gurke, Tomate, gern Paprika' },
      { item: 'zwiebeln', amount: 40, note: 'am besten rote Zwiebel' },
      { item: 'feta_light', amount: 40, note: 'zerbröselt' },
      { item: 'oel', amount: 2 },
      { item: 'gewuerz', amount: 0, text: 'Limettensaft, geräuchertes Paprikapulver oder Chipotle, Kreuzkümmel, Petersilie oder Koriander, Salz' },
    ],
    steps: [
      'Bohnen und Mais abspülen und gut abtropfen lassen.',
      'Gemüse, Zwiebel und Hähnchen so klein würfeln wie die Bohnen.',
      'Alles mit Feta, Öl, Limettensaft und Gewürzen in eine Dose geben, Deckel drauf, kräftig schütteln und 10 Minuten ziehen lassen.',
    ],
    tip: 'Alles so klein schneiden wie die Bohnen, dann hat jeder Löffel von allem etwas, und im Kühlschrank zieht der Salat 3 Tage lang immer besser durch.',
  },
  haehnchen_fajita_quesadilla: {
    name: 'Hähnchen-Fajita-Quesadilla', slot: 'haupt', device: 'herd', alt: ['airfryer'], time: 15, proteins: ['haehnchen', 'milch'], viral: true,
    ingredients: [
      { item: 'wraps', amount: 2, side: [1, 4, 1] },
      { item: 'haehnchenbrust', amount: 140, note: 'in Streifen' },
      { item: 'tk_paprika', amount: 150 },
      { item: 'zwiebeln', amount: 50, note: 'in Streifen' },
      { item: 'kaese_light', amount: 30 },
      { item: 'skyr', amount: 50, note: 'mit Honig und Chipotle als Dip' },
      { item: 'honig', amount: 1 },
      { item: 'oel', amount: 1 },
      { item: 'gewuerz', amount: 0, text: 'Fajita-Gewürz (Paprika, Kreuzkümmel, Knoblauch), Chipotle- oder Chilipulver, Salz' },
    ],
    steps: [
      'Hähnchenstreifen mit Öl und Fajita-Gewürz mischen und in der Pfanne 5 Minuten scharf anbraten. Paprika und Zwiebel dazu und 4 Minuten mitbraten, bis innen nichts mehr rosa ist.',
      'Füllung herausnehmen. Jeden Wrap zur Hälfte mit Käse, Füllung und noch etwas Käse belegen und zuklappen.',
      'In der trockenen Pfanne bei mittlerer Hitze von jeder Seite 2–3 Minuten braten, bis der Käse schmilzt, dann in Dreiecke schneiden.',
      'Skyr mit Honig, Chipotle und einer Prise Salz zum Dip verrühren.',
    ],
    tip: 'Das Fajita-Gemüse kommt mit in die Quesadilla und der süß-rauchige Honig-Chipotle-Dip daneben zum Eintunken, genau das war der Hack.',
  },
  philly_cheesesteak_paprika: {
    name: 'Philly-Cheesesteak-Paprika', slot: 'haupt', device: 'ofen', alt: ['airfryer'], time: 15, proteins: ['rind', 'milch'], viral: true,
    ingredients: [
      { item: 'paprikaschote', amount: 2, note: 'halbiert und entkernt' },
      { item: 'rinderhuefte', amount: 180, note: 'hauchdünn geschnitten' },
      { item: 'zwiebeln', amount: 80, note: 'in Streifen' },
      { item: 'champignons', amount: 150, note: 'in Scheiben' },
      { item: 'kaese_light', amount: 40, note: 'statt Provolone' },
      { item: 'oel', amount: 1 },
      { item: 'reis', amount: 70, side: [40, 180] },
      { item: 'gewuerz', amount: 0, text: 'Salz, Pfeffer, Knoblauchpulver, 1 TL Worcestersauce' },
    ],
    steps: [
      'Reis im Reiskocher starten. Paprikahälften bei 200 °C Umluft 10 Minuten im Ofen vorgaren.',
      'Inzwischen Zwiebel und Pilze im Öl 5 Minuten braten, das Fleisch dazu, 2 Minuten scharf mitbraten und würzen.',
      'Füllung in die Paprikahälften, Käse drauf und 8 Minuten überbacken, bis er blubbert.',
    ],
    tip: 'Das Steak 20 Minuten ins Gefrierfach legen, dann lässt es sich hauchdünn schneiden und wird zart wie im Original.',
  },
  oyakodon: {
    name: 'Oyakodon (Hähnchen-Ei-Reis)', slot: 'haupt', device: 'herd', time: 15, proteins: ['haehnchen', 'ei'], viral: true,
    ingredients: [
      { item: 'reis', amount: 75, side: [40, 180] },
      { item: 'haehnchenschenkel', amount: 180, note: 'in mundgerechten Stücken' },
      { item: 'eier', amount: 2 },
      { item: 'zwiebeln', amount: 100, note: 'in Streifen' },
      { item: 'sojasauce', amount: 2 },
      { item: 'bruehe', amount: 1 },
      { item: 'honig', amount: 1 },
      { item: 'rohkost', amount: 150, note: 'Gurke, mit etwas Reisessig und Salz' },
      { item: 'gewuerz', amount: 0, text: 'Frühlingszwiebel, nach Wunsch 1 EL Mirin' },
    ],
    steps: [
      'Reis waschen und mit so viel Wasser wie immer in den Reiskocher geben.',
      'Zwiebel mit 100 ml Wasser, Brühe, Sojasauce und Honig in einer kleinen Pfanne aufkochen. Hähnchen rein, Deckel drauf, 7 Minuten köcheln. Aufschneiden: Innen darf nichts mehr rosa sein.',
      'Eier nur grob verquirlen, in zwei Portionen darübergießen, Deckel drauf und 1–2 Minuten stocken lassen.',
      'Alles samt Sud auf den Reis gleiten lassen, Frühlingszwiebel drüber, Gurke dazu.',
    ],
    tip: 'Die Eier nur ein paar Mal mit Stäbchen durchziehen, sodass Eiweiß und Eigelb streifig bleiben, und in zwei Schüben eingießen, so wird die Eidecke seidig wie im Original.',
  },
  bieber_haehnchenbaellchen: {
    name: 'Hailey-Bieber-Hähnchenbällchen mit Hüttenkäse', slot: 'haupt', device: 'herd', alt: ['ofen'], time: 15, proteins: ['pute', 'milch'], viral: true,
    ingredients: [
      { item: 'nudeln', amount: 70, side: [40, 180] },
      { item: 'putenhack', amount: 180, note: 'zu 8 Bällchen geformt' },
      { item: 'huettenkaese', amount: 100 },
      { item: 'parmesan', amount: 10, note: 'fein gerieben' },
      { item: 'tomaten', amount: 300 },
      { item: 'oel', amount: 1 },
      { item: 'gewuerz', amount: 0, text: 'Knoblauch, Oregano, Salz, Pfeffer, Basilikum' },
    ],
    steps: [
      'Nudeln kochen. Hack mit der Hälfte des Parmesans, Knoblauch, Oregano und Salz verkneten und mit nassen Händen zu 8 Bällchen formen.',
      'Bällchen im Öl rundum 5 Minuten anbraten, Tomaten dazu, Deckel drauf und 10 Minuten köcheln. Ein Bällchen aufschneiden: Innen darf nichts mehr rosa sein.',
      'Hüttenkäse in Klecksen auf die Soße setzen, restlichen Parmesan und Basilikum drüber und mit den Nudeln essen.',
    ],
    tip: 'Den Hüttenkäse nicht unterrühren, sondern in Klecksen auf die heiße Soße setzen, dann bleibt er cremig und gibt jedem Bissen den typischen Kontrast zur würzigen Tomate.',
  },
  swamp_soup: {
    name: 'Grüne Hähnchen-Reis-Suppe (Swamp Soup)', slot: 'haupt', device: 'herd', time: 15, proteins: ['haehnchen'], viral: true,
    ingredients: [
      { item: 'haehnchenbrust', amount: 220, note: 'am Stück' },
      { item: 'reis', amount: 80, side: [40, 180] },
      { item: 'tk_spinat', amount: 200 },
      { item: 'zwiebeln', amount: 50 },
      { item: 'bruehe', amount: 2 },
      { item: 'oel', amount: 2 },
      { item: 'gewuerz', amount: 0, text: '3 Knoblauchzehen, 1 daumengroßes Stück Ingwer, 1 Bund Petersilie, 3 Frühlingszwiebeln, Zitrone, Salz' },
    ],
    steps: [
      'Zwiebel würfeln und in 1 TL Öl im Topf andünsten. 1 l Wasser, Brühe, Reis und die ganze Hähnchenbrust dazu und 15 Minuten leise köcheln.',
      'Spinat antauen lassen und mit Knoblauch, Ingwer, Petersilie, Frühlingszwiebeln, 1 TL Öl und einer Kelle Brühe mit dem Stabmixer fein pürieren.',
      'Hähnchen herausnehmen und zerzupfen, innen darf nichts mehr rosa sein. Mit dem grünen Püree zurück in den Topf, nicht mehr kochen und mit Zitrone und Salz abschmecken.',
    ],
    tip: 'Das grüne Püree erst ganz am Schluss einrühren und nicht mehr kochen lassen, so bleiben Knoblauch und Ingwer frisch und die Suppe knallgrün.',
  },
  tomaten_ruehrei_reis: {
    name: 'Chinesisches Tomaten-Rührei mit Reis', slot: 'haupt', device: 'herd', time: 10, proteins: ['ei'], viral: true,
    ingredients: [
      { item: 'reis', amount: 70, side: [40, 180] },
      { item: 'eier', amount: 3 },
      { item: 'eiklar', amount: 200 },
      { item: 'tomaten_frisch', amount: 400, note: 'in Spalten' },
      { item: 'oel', amount: 2 },
      { item: 'honig', amount: 1, note: 'statt Zucker' },
      { item: 'gewuerz', amount: 0, text: 'Frühlingszwiebel, Salz' },
    ],
    steps: [
      'Reis im Reiskocher starten.',
      'Eier mit Eiklar und einer Prise Salz verquirlen, in 1 TL heißem Öl in großen, weichen Flocken stocken lassen und herausnehmen.',
      'Tomaten mit 1 TL Öl, Honig, Salz und 3 EL Wasser 4 Minuten schmoren, bis sie saftig zerfallen.',
      'Ei zurück in die Pfanne, 1 Minute unterheben, bis es ganz gestockt ist, Frühlingszwiebel drüber und auf den Reis.',
    ],
    tip: 'Die Eier nur zu drei Vierteln stocken lassen und herausnehmen, sie garen in der Tomatensoße fertig und bleiben so fluffig.',
  },
  steakwuerfel_knoblauch: {
    name: 'Knoblauch-Steakwürfel aus dem Airfryer', slot: 'haupt', device: 'airfryer', alt: ['ofen'], time: 10, proteins: ['rind'], viral: true,
    ingredients: [
      { item: 'rinderhuefte', amount: 200, note: 'in 2–3-cm-Würfeln' },
      { item: 'kartoffeln', amount: 350, side: [200, 900, 50], note: 'am besten Drillinge' },
      { item: 'tk_brokkoli', amount: 250 },
      { item: 'butter', amount: 10 },
      { item: 'oel', amount: 1 },
      { item: 'gewuerz', amount: 0, text: '2 Knoblauchzehen, Petersilie, Salz, Pfeffer' },
    ],
    steps: [
      'Drillinge halbieren, mit dem Öl und Salz mischen und bei 200 °C etwa 22 Minuten in den Airfryer. Brokkoli nach 10 Minuten dazu, danach alles herausnehmen und warm halten.',
      'Steakwürfel salzen, pfeffern und allein bei 200 °C 6–7 Minuten in den Airfryer, nach der Hälfte schütteln.',
      'Butter mit gepresstem Knoblauch und Petersilie kurz in der Mikrowelle schmelzen und die heißen Würfel darin schwenken.',
    ],
    tip: 'Die Würfel vorher trocken tupfen und mit Abstand in den Korb legen, dann bekommen sie außen Kruste und bleiben innen rosa.',
  },
  chopped_italian_sandwich: {
    name: 'Chopped-Italian-Sandwich leicht', slot: 'haupt', device: 'ohne', time: 10, proteins: ['pute', 'schwein', 'milch'], viral: true,
    ingredients: [
      { item: 'broetchen', amount: 2, side: [1, 4, 1] },
      { item: 'putenaufschnitt', amount: 100 },
      { item: 'kochschinken', amount: 60 },
      { item: 'kaese_light', amount: 40, note: 'statt Provolone' },
      { item: 'rohkost', amount: 200, note: 'Eisbergsalat, Tomate, rote Zwiebel' },
      { item: 'skyr', amount: 60, note: 'als Dressing' },
      { item: 'oel', amount: 1 },
      { item: 'gewuerz', amount: 0, text: 'Peperoni aus dem Glas, Rotweinessig, Oregano, Knoblauch, Salz, Pfeffer' },
    ],
    steps: [
      'Salat, Tomate, Zwiebel, ein paar Peperoni, Aufschnitt und Schinken auf einem großen Brett mit einem großen Messer grob durchhacken, Käse drüberstreuen.',
      'Skyr, Öl, einen Schuss Rotweinessig, Oregano, Knoblauch, Salz und Pfeffer drauf und weiterhacken, bis alles gleichmäßig gemischt ist.',
      'Brötchen aufschneiden, nach Wunsch kurz aufbacken, und die Mischung hineinfüllen.',
    ],
    tip: 'Das Dressing direkt auf dem Brett mit einhacken statt es obendrauf zu geben, so schmeckt jeder Bissen gleich, und genau das macht das Chopped Sandwich aus.',
  },
  reiskocher_bratreis: {
    name: 'Reiskocher-Bratreis mit Hähnchen und Ei', slot: 'haupt', device: 'reiskocher', time: 10, proteins: ['haehnchen', 'ei'], viral: true,
    ingredients: [
      { item: 'reis', amount: 75, side: [40, 180] },
      { item: 'haehnchenbrust', amount: 170, note: 'in kleinen Würfeln' },
      { item: 'eier', amount: 2 },
      { item: 'tk_gemuese_mix', amount: 200, note: 'am besten Erbsen, Möhren, Mais' },
      { item: 'sojasauce', amount: 2 },
      { item: 'oel', amount: 1, note: 'am besten Sesamöl' },
      { item: 'gewuerz', amount: 0, text: 'Knoblauch, Frühlingszwiebel, Pfeffer' },
    ],
    steps: [
      'Reis waschen und mit etwas weniger Wasser als sonst in den Reiskocher geben, Sojasauce, Sesamöl und Knoblauch einrühren.',
      'TK-Gemüse gefroren obendrauf, Hähnchenwürfel darauf verteilen, die Eier obendrauf aufschlagen und Reiskocher starten.',
      'Nach dem Kochen alles kräftig durchmischen, sodass das Ei in Stücke zerfällt. Das größte Hähnchenstück aufschneiden: Innen darf nichts mehr rosa sein.',
    ],
    tip: 'Nach dem Kochen den Deckel 5 Minuten offen lassen und erst dann durchmischen, so dampft der Reis ab und wird körnig wie Bratreis statt matschig.',
  },
  pfeffer_haehnchen: {
    name: 'Pfeffer-Hähnchen (Chicken au Poivre) leicht', slot: 'haupt', device: 'ofen', alt: ['airfryer'], time: 15, proteins: ['haehnchen'], viral: true,
    ingredients: [
      { item: 'haehnchenschenkel', amount: 220 },
      { item: 'kartoffeln', amount: 350, side: [200, 900, 50] },
      { item: 'tk_brokkoli', amount: 250 },
      { item: 'kochcreme', amount: 50 },
      { item: 'zwiebeln', amount: 30, note: 'oder 1 Schalotte' },
      { item: 'bruehe', amount: 1 },
      { item: 'oel', amount: 1 },
      { item: 'gewuerz', amount: 0, text: '2 TL schwarze Pfefferkörner, 1 TL Senf, Salz, nach Wunsch ein Schuss Weinbrand' },
    ],
    steps: [
      'Kartoffeln in Spalten schneiden, mit dem Öl und Salz aufs Blech und bei 200 °C Umluft in den Ofen.',
      'Pfeffer grob zerstoßen, Hähnchen salzen und die Hälfte des Pfeffers auf beiden Seiten andrücken. Nach 10 Minuten mit dem Brokkoli aufs Blech und etwa 20 Minuten mitgaren. Aufschneiden: Innen darf nichts mehr rosa sein.',
      'Zwiebel fein würfeln und mit 100 ml Wasser, Brühe, Senf und restlichem Pfeffer in einer kleinen Pfanne aufkochen. Kochsahne rein, 3 Minuten sämig einkochen und über das Hähnchen gießen.',
    ],
    tip: 'Den Pfeffer im Gefrierbeutel mit dem Topfboden grob zerdrücken statt ihn zu mahlen, so wird die Kruste aromatisch-knackig statt nur scharf wie beim echten Au Poivre.',
  },
  zitronen_haehnchen_reis: {
    name: 'Griechisches Zitronen-Hähnchen mit Reis', slot: 'haupt', device: 'herd', alt: ['reiskocher'], time: 15, proteins: ['haehnchen'], viral: true,
    ingredients: [
      { item: 'haehnchenschenkel', amount: 240 },
      { item: 'reis', amount: 80, side: [30, 200] },
      { item: 'zitrone', amount: 1, note: 'Schale abreiben, Saft auspressen' },
      { item: 'zwiebeln', amount: 50 },
      { item: 'bruehe', amount: 1 },
      { item: 'oel', amount: 1 },
      { item: 'rohkost', amount: 200, note: 'Gurke und Tomate' },
      { item: 'gewuerz', amount: 0, text: '2 Knoblauchzehen, 1 TL Oregano, Salz, Pfeffer' },
    ],
    steps: [
      'Hähnchen mit der Hälfte vom Zitronensaft, Knoblauch, Oregano und Salz mischen.',
      'Im Öl in einem Topf mit Deckel 2 Minuten pro Seite goldbraun anbraten und herausnehmen.',
      'Zwiebel im selben Topf kurz anschwitzen. Reis, die doppelte Menge Wasser, Brühe und Zitronenschale dazu, Hähnchen obendrauf, Deckel drauf und 20 Minuten bei kleiner Hitze garen.',
      'Aufschneiden: Innen darf nichts mehr rosa sein. Restlichen Zitronensaft drüber, Gurke und Tomate dazu.',
    ],
    tip: 'Den Reis im selben Topf garen, in dem das Hähnchen angebraten wurde: Er saugt den ganzen Bratensatz auf und wird dadurch so würzig.',
  },
  backpapier_doener: {
    name: 'Backpapier-Döner mit Rinderhack', slot: 'haupt', device: 'ofen', alt: ['airfryer'], time: 15, proteins: ['rind', 'milch'], viral: true,
    ingredients: [
      { item: 'rinderhack', amount: 200 },
      { item: 'zwiebeln', amount: 50, note: 'fein gerieben' },
      { item: 'skyr', amount: 150, note: '1 EL ins Fleisch, der Rest mit Knoblauch als Soße' },
      { item: 'fladenbrot', amount: 100, side: [40, 240] },
      { item: 'rohkost', amount: 200, note: 'Salat, Tomate, Gurke, etwas Rotkohl' },
      { item: 'gewuerz', amount: 0, text: 'Dönergewürz oder Paprika, Kreuzkümmel und Oregano, Salz, Knoblauch für die Soße' },
    ],
    steps: [
      'Hack mit Zwiebel, 1 EL Skyr, Gewürzen und Salz gründlich verkneten.',
      'Zwischen zwei Backpapieren mit dem Nudelholz ganz flach ausrollen, das obere Papier abziehen und das Fleisch zusammen mit dem unteren Papier fest aufrollen.',
      'Die Rolle bei 200 °C Ober-/Unterhitze 20 Minuten in den Ofen, das Fladenbrot für die letzten 5 Minuten dazu. Fleisch vom Papier lösen: Innen darf nichts mehr rosa sein.',
      'In dünne Streifen schneiden und mit Salat und Knoblauch-Skyr ins Fladenbrot füllen.',
    ],
    tip: 'Das Papier wird mit eingerollt: So gart das Hack in hauchdünnen Lagen und zerfällt beim Schneiden in echte Dönerstreifen.',
  },
  rind_brokkoli: {
    name: 'Rind mit Brokkoli', slot: 'haupt', device: 'herd', time: 15, proteins: ['rind'], viral: true,
    ingredients: [
      { item: 'rinderhuefte', amount: 200, note: 'in dünnen Streifen' },
      { item: 'reis', amount: 80, side: [30, 200] },
      { item: 'tk_brokkoli', amount: 300 },
      { item: 'sojasauce', amount: 2 },
      { item: 'austernsosse', amount: 1 },
      { item: 'honig', amount: 1 },
      { item: 'oel', amount: 1 },
      { item: 'gewuerz', amount: 0, text: '2 Knoblauchzehen, 1 TL Ingwer, 1 TL Speisestärke' },
    ],
    steps: [
      'Reis im Reiskocher starten.',
      'Rind quer zur Faser in dünne Streifen schneiden und mit 1 EL Sojasauce und der Stärke mischen.',
      'Brokkoli mit 3 EL Wasser in der Pfanne mit Deckel 4 Minuten dämpfen und herausnehmen.',
      'Öl stark erhitzen, Rind 2 Minuten scharf anbraten. Knoblauch, Ingwer, Austernsoße, restliche Sojasauce, Honig und 3 EL Wasser dazu, Brokkoli unterheben und 1 Minute köcheln, bis die Soße glänzt.',
    ],
    tip: 'Die Stärke am Fleisch ist der Trick vom Chinaimbiss: Die Streifen bleiben zart und die Soße bindet von allein.',
  },
  dirty_spaghetti: {
    name: 'Dirty Spaghetti leicht', slot: 'haupt', device: 'herd', time: 20, proteins: ['rind', 'haehnchen'], viral: true,
    ingredients: [
      { item: 'nudeln', amount: 90, side: [35, 210], note: 'Spaghetti' },
      { item: 'rinderhack', amount: 170 },
      { item: 'gefluegelwiener', amount: 40, note: 'in Scheiben, statt Räucherwurst' },
      { item: 'tk_paprika', amount: 150 },
      { item: 'zwiebeln', amount: 50 },
      { item: 'weizenmehl', amount: 10, note: 'etwa 1 EL, für die schnelle Mehlschwitze' },
      { item: 'tomatenmark', amount: 1 },
      { item: 'bruehe', amount: 1 },
      { item: 'gewuerz', amount: 0, text: '1–2 TL Cajun-Gewürz (oder Paprika edelsüß, Knoblauch, Oregano, Cayenne), Salz, Petersilie zum Bestreuen' },
    ],
    steps: [
      'Spaghetti kochen, vor dem Abgießen eine Tasse Nudelwasser aufheben.',
      'Hack und Wurstscheiben ohne Öl in der Pfanne braun und krümelig braten, bis nichts mehr rosa ist. Zwiebel und Paprika dazu und 3 Minuten mitbraten.',
      'Mehl, Tomatenmark und Cajun-Gewürz drüberstreuen und unter Rühren 2 Minuten anrösten, bis es nussig riecht. 250 ml Wasser mit der Brühe einrühren und 5 Minuten sämig köcheln.',
      'Spaghetti und einen Schuss Nudelwasser unterheben, bis die Soße an den Nudeln haftet, Petersilie drüber.',
    ],
    tip: 'Das Mehl im Bratfett von Hack und Wurst braun anzurösten ist die schnelle Cajun-Mehlschwitze aus dem Original: Sie macht die Soße dunkel, nussig und „dirty“ und lässt sie an den Spaghetti kleben.',
  },
  puten_feta_baellchen: {
    name: 'Puten-Feta-Spinat-Bällchen', slot: 'haupt', device: 'airfryer', alt: ['ofen'], time: 15, proteins: ['pute', 'milch'], viral: true,
    ingredients: [
      { item: 'putenhack', amount: 200 },
      { item: 'feta_light', amount: 40, note: 'zerbröselt' },
      { item: 'tk_spinat', amount: 100, note: 'aufgetaut und gut ausgedrückt' },
      { item: 'reis', amount: 70, side: [30, 180] },
      { item: 'skyr', amount: 100, note: 'mit Gurke, Knoblauch und Dill als Tzatziki' },
      { item: 'rohkost', amount: 150, note: 'Gurke und Tomate' },
      { item: 'gewuerz', amount: 0, text: 'Knoblauch, Oregano, Dill, Salz, Pfeffer' },
    ],
    steps: [
      'Reis waschen und mit so viel Wasser wie immer in den Reiskocher geben.',
      'Hack mit Spinat, Feta, Knoblauch, Oregano und wenig Salz verkneten und mit nassen Händen zu 10 Bällchen formen.',
      'Bei 200 °C etwa 12 Minuten in den Airfryer, nach der Hälfte schütteln. Eins aufbrechen: Innen darf nichts mehr rosa sein.',
      'Skyr mit etwas geriebener Gurke, Knoblauch und Dill verrühren und mit Reis und dem Rest vom Salat essen.',
    ],
    tip: 'Den aufgetauten Spinat im Küchentuch richtig trocken ausdrücken, sonst werden die Bällchen matschig und fallen auseinander.',
  },
  gochujang_bowl: {
    name: 'Gochujang-Brühe-Bowl mit Rinderhack', slot: 'haupt', device: 'herd', time: 15, proteins: ['rind'], viral: true,
    ingredients: [
      { item: 'rinderhack', amount: 200 },
      { item: 'reis', amount: 80, side: [30, 200] },
      { item: 'tk_brokkoli', amount: 200 },
      { item: 'gochujang', amount: 1 },
      { item: 'honig', amount: 1 },
      { item: 'sojasauce', amount: 1 },
      { item: 'bruehe', amount: 1 },
      { item: 'gewuerz', amount: 0, text: 'Knoblauch, Ingwer, Frühlingszwiebeln, Sesam' },
    ],
    steps: [
      'Reis im Reiskocher starten.',
      'Hack ohne Öl im Topf krümelig braten, bis nichts mehr rosa ist. Gochujang, Honig, Sojasauce und Knoblauch dazu, 1 Minute rösten, bis alles glänzt, und herausnehmen.',
      'Im selben Topf 300 ml Wasser mit Brühe und Ingwer aufkochen und den Brokkoli darin 4 Minuten garen.',
      'Reis in eine tiefe Schale, Hack und Brokkoli drauf, heiße Brühe angießen, Frühlingszwiebeln und Sesam drüber.',
    ],
    tip: 'Die Brühe im Hacktopf aufkochen: Sie löst die angerösteten Gochujang-Reste vom Boden und schmeckt dann nach viel mehr als nach Brühpulver.',
  },
  blech_kafta: {
    name: 'Blech-Kafta mit Joghurtsauce', slot: 'haupt', device: 'ofen', alt: ['airfryer'], time: 15, proteins: ['rind', 'milch'], viral: true,
    ingredients: [
      { item: 'rinderhack', amount: 200 },
      { item: 'zwiebeln', amount: 50, note: 'fein gerieben und ausgedrückt' },
      { item: 'kartoffeln', amount: 300, side: [100, 900, 50] },
      { item: 'skyr', amount: 150, note: 'mit Knoblauch und Zitrone als Soße' },
      { item: 'rohkost', amount: 150, note: 'Tomaten halbiert mit aufs Blech, Gurke frisch dazu' },
      { item: 'oel', amount: 1 },
      { item: 'gewuerz', amount: 0, text: '1 Bund Petersilie, 1 TL Kreuzkümmel, 1 TL Paprika, 1 Prise Zimt, Knoblauch, Salz, Spritzer Zitrone' },
    ],
    steps: [
      'Kartoffeln in dünne Spalten schneiden, mit Öl und Salz auf eine Blechhälfte legen und bei 200 °C Umluft 10 Minuten vorbacken.',
      'Hack mit Zwiebel, gehackter Petersilie, Gewürzen und Salz verkneten, auf der freien Blechhälfte 1 cm dick flach drücken und mit dem Messer in Rauten einritzen. Die halbierten Tomaten mit der Schnittfläche nach oben daneben legen.',
      'Alles weitere 15 Minuten backen, bis das Fleisch innen nicht mehr rosa ist.',
      'Skyr mit Knoblauch, Zitrone und Salz verrühren und mit Kartoffeln, Tomaten und Gurke zur Kafta essen.',
    ],
    tip: 'Die Hackplatte vor dem Backen in Stücke ritzen: So sparst du dir das Spieße-Formen und sie zerfällt danach sauber in Portionen.',
  },
  lachs_bowl_mariko: {
    name: 'Lachs-Reis-Bowl nach Emily Mariko', slot: 'haupt', device: 'reiskocher', alt: ['airfryer'], time: 10, proteins: ['fisch', 'milch'], viral: true,
    ingredients: [
      { item: 'reis', amount: 70, side: [30, 180] },
      { item: 'lachs', amount: 150 },
      { item: 'sojasauce', amount: 1 },
      { item: 'skyr', amount: 100, note: 'mit Sriracha verrührt statt Mayo' },
      { item: 'nori', amount: 2, note: 'geviertelt' },
      { item: 'avocado', amount: 40 },
      { item: 'rohkost', amount: 200, note: 'Gurke, wer mag mit Kimchi' },
      { item: 'gewuerz', amount: 0, text: 'Sriracha, Sesam' },
    ],
    steps: [
      'Reis waschen und mit so viel Wasser wie immer in den Reiskocher geben.',
      'Den gefrorenen Lachs obendrauf legen und den Reiskocher starten.',
      'Lachs und Reis in der Schale mit der Gabel zerdrücken und Sojasauce drüber. Skyr mit Sriracha verrühren und drüberziehen.',
      'Gurke und Avocado in Scheiben dazu, mit den Nori-Stücken Häppchen greifen und essen.',
    ],
    tip: 'Emilys Trick für Reste: Einen Eiswürfel auf den Reis legen, mit Backpapier abdecken und kurz in die Mikrowelle, der Dampf macht den Reis wieder fluffig.',
  },
  fruehlingsrollen_bowl: {
    name: 'Frühlingsrollen-Bowl mit Hack und Kohl', slot: 'haupt', device: 'herd', time: 15, proteins: ['pute'], viral: true,
    ingredients: [
      { item: 'putenhack', amount: 200 },
      { item: 'weisskohl', amount: 300, note: 'in feinen Streifen' },
      { item: 'reis', amount: 70, side: [0, 180] },
      { item: 'sojasauce', amount: 2 },
      { item: 'oel', amount: 2, note: 'am besten geröstetes Sesamöl' },
      { item: 'gewuerz', amount: 0, text: '2 Knoblauchzehen, 1 TL Ingwer, Frühlingszwiebeln, Sriracha nach Geschmack' },
    ],
    steps: [
      'Reis im Reiskocher starten.',
      'Hack mit 1 TL Öl in einer großen Pfanne krümelig braten, bis nichts mehr rosa ist.',
      'Kohl, Knoblauch und Ingwer dazu und 5 Minuten braten, bis der Kohl zusammenfällt, aber noch Biss hat.',
      'Mit Sojasauce und dem restlichen Sesamöl abschmecken, Frühlingszwiebeln drüber und mit dem Reis essen.',
    ],
    tip: 'Das Sesamöl erst ganz am Ende drüberträufeln: Dann schmeckt die Pfanne wie die Füllung einer echten Frühlingsrolle.',
  },
  gurkensalat_lachs: {
    name: 'Gurkensalat mit Räucherlachs', slot: 'snack', device: 'ohne', time: 5, proteins: ['fisch', 'milch'], viral: true,
    ingredients: [
      { item: 'gurke', amount: 1 },
      { item: 'raeucherlachs', amount: 80, note: 'in Streifen gezupft' },
      { item: 'frischkaese_light', amount: 30 },
      { item: 'sojasauce', amount: 1 },
      { item: 'gewuerz', amount: 0, text: '1 TL Reisessig, ein paar Tropfen Sesamöl, 1 TL Sesam, Dill, Chiliflocken' },
    ],
    steps: [
      'Gurke mit dem Gemüsehobel in hauchdünnen Scheiben direkt in eine große Dose mit Deckel hobeln.',
      'Sojasauce, Essig, Sesamöl, Sesam und Dill dazugeben, Deckel drauf und kräftig schütteln.',
      'Räucherlachs und kleine Kleckse Frischkäse obendrauf verteilen und direkt aus der Dose essen.',
    ],
    tip: 'Wie im Original hobeln statt schneiden und in der geschlossenen Dose schütteln: Die dünnen Scheiben saugen das Dressing in Sekunden auf, ganz ohne Schüssel.',
  },
  huettenkaese_pizza: {
    name: 'Hüttenkäse-Pizza-Bowl', slot: 'snack', device: 'airfryer', alt: ['ofen'], time: 5, proteins: ['milch', 'pute'], viral: true,
    ingredients: [
      { item: 'huettenkaese', amount: 150 },
      { item: 'tomaten', amount: 40, note: 'oder Pizzatomaten' },
      { item: 'kaese_light', amount: 20 },
      { item: 'putensalami', amount: 15 },
      { item: 'gewuerz', amount: 0, text: 'Oregano, Knoblauchpulver, Chiliflocken' },
    ],
    steps: [
      'Hüttenkäse mit Oregano und Knoblauchpulver verrühren und in eine kleine ofenfeste Schale streichen.',
      'Tomaten darauf verteilen, Käse drüberstreuen und die Salamischeiben obenauf legen.',
      'Bei 180 °C 8–10 Minuten in den Airfryer, bis der Käse blubbert (Ofen: 200 °C, etwa 12 Minuten).',
    ],
    tip: 'Die Salami ganz obenauf legen: In der heißen Luft wölben sich die Ränder und werden knusprig wie auf einer echten Pizza.',
  },
  huettenkaese_eis: {
    name: 'Hüttenkäse-Eis mit Erdbeeren', slot: 'snack', device: 'ohne', time: 5, proteins: ['milch'], viral: true,
    ingredients: [
      { item: 'huettenkaese', amount: 150 },
      { item: 'erdbeeren', amount: 80, note: 'frisch oder TK' },
      { item: 'honig', amount: 2 },
    ],
    steps: [
      'Hüttenkäse, Honig und die Hälfte der Erdbeeren mit dem Pürierstab pürieren, bis die Masse ganz glatt ist.',
      'Restliche Erdbeeren klein schneiden, unterheben und alles in eine flache Dose füllen.',
      'Mindestens 3 Stunden ins Gefrierfach und vor dem Essen 10 Minuten antauen lassen.',
    ],
    tip: 'Pürier so lange, bis kein Körnchen mehr zu sehen ist: Nur dann wird es cremig wie Softeis statt körnig.',
  },
  skyr_lotus_cheesecake: {
    name: 'Skyr-Lotus-Cheesecake im Glas', slot: 'snack', device: 'ohne', time: 3, proteins: ['milch'], viral: true,
    ingredients: [
      { item: 'skyr', amount: 200 },
      { item: 'karamellkekse', amount: 3 },
    ],
    steps: [
      'Skyr glatt rühren und in ein Glas füllen.',
      'Zwei Kekse senkrecht hineindrücken, bis sie ganz bedeckt sind. Deckel drauf und über Nacht in den Kühlschrank.',
      'Morgens den dritten Keks darüberbröseln.',
    ],
    tip: 'Nicht umrühren: Über Nacht ziehen die Kekse Feuchtigkeit aus dem Skyr, er wird fest wie Käsekuchen und die Kekse weich wie ein Kuchenboden.',
  },
  skyr_schoko_cluster: {
    name: 'Erdbeer-Skyr-Schoko-Cluster', slot: 'snack', device: 'ohne', time: 10, proteins: ['milch'], viral: true,
    ingredients: [
      { item: 'skyr', amount: 150 },
      { item: 'erdbeeren', amount: 120 },
      { item: 'zartbitter', amount: 20 },
      { item: 'honig', amount: 1 },
    ],
    steps: [
      'Erdbeeren klein würfeln und mit Skyr und Honig verrühren.',
      'Mit einem Esslöffel kleine Häufchen auf Backpapier setzen und 1 Stunde einfrieren.',
      'Schokolade in der Mikrowelle in 20-Sekunden-Schritten schmelzen, über die gefrorenen Häufchen träufeln und zurück ins Gefrierfach.',
      'Vor dem Essen 5 Minuten antauen lassen.',
    ],
    tip: 'Die Häufchen erst ganz durchfrieren: Auf dem eiskalten Skyr wird die Schokolade sofort fest und knackt beim Reinbeißen.',
  },
  huettenkaese_keksteig: {
    name: 'Hüttenkäse-Keksteig', slot: 'snack', device: 'ohne', time: 5, proteins: ['milch'], viral: true,
    ingredients: [
      { item: 'huettenkaese', amount: 100 },
      { item: 'whey', amount: 15, note: 'am besten Vanille- oder Cookie-Geschmack, süßt schon' },
      { item: 'erdnussbutter', amount: 1 },
      { item: 'zartbitter', amount: 8, note: 'zwei Stückchen, fein gehackt' },
      { item: 'gewuerz', amount: 0, text: '1 Prise Salz, nach Wunsch ein paar Tropfen Vanille' },
    ],
    steps: [
      'Hüttenkäse, Erdnussbutter und Salz mit dem Pürierstab ganz glatt pürieren.',
      'Whey unterrühren, bis eine dicke, glatte Masse entsteht, dann die gehackte Schokolade unterheben.',
      'Mindestens 30 Minuten kalt stellen, dann zieht die Masse an und wird löffelfest wie Keksteig.',
    ],
    tip: 'Pürier den Hüttenkäse, bis kein Körnchen mehr zu sehen ist, und lass ihn gut durchkühlen: Erst dann verschwindet der Hüttenkäse-Geschmack und es schmeckt nach rohem Keksteig.',
  },
  mayak_eier: {
    name: 'Mayak-Eier (koreanische Soja-Eier)', slot: 'snack', device: 'herd', time: 10, proteins: ['ei'], viral: true,
    ingredients: [
      { item: 'eier', amount: 3 },
      { item: 'sojasauce', amount: 2 },
      { item: 'honig', amount: 1 },
      { item: 'fruehlingszwiebeln', amount: 1, note: 'in feinen Ringen' },
      { item: 'gewuerz', amount: 0, text: '1 Knoblauchzehe, ½ rote Chili, 1 TL Sesam' },
    ],
    steps: [
      'Eier in kochendes Wasser legen, genau 6½ Minuten kochen und sofort in eiskaltes Wasser.',
      'Sojasauce, 2 EL Wasser, Honig, gehackten Knoblauch, Frühlingszwiebel, Chili und Sesam in einem kleinen Gefrierbeutel verrühren.',
      'Eier schälen und in den Beutel legen, die Luft herausdrücken und verschließen: So sind sie trotz wenig Marinade ganz bedeckt. Mindestens 4 Stunden, am besten über Nacht, in den Kühlschrank.',
    ],
    tip: 'Mayak heißt auf Koreanisch „Droge“, süchtig macht das wachsweiche Eigelb: also wirklich nur 6½ Minuten kochen und sofort ins Eiswasser.',
  },
  thunfischsalat_mcconaughey: {
    name: 'McConaughey-Thunfischsalat', slot: 'snack', device: 'ohne', time: 10, proteins: ['fisch', 'milch'], viral: true,
    ingredients: [
      { item: 'thunfisch', amount: 1 },
      { item: 'skyr', amount: 50 },
      { item: 'apfel', amount: 1, note: 'klein und säuerlich, fein gewürfelt' },
      { item: 'zwiebeln', amount: 20, note: 'rote Zwiebel, fein gewürfelt' },
      { item: 'mais', amount: 20 },
      { item: 'gewuerz', amount: 0, text: '1 Gewürzgurke, ½ TL Wasabi-Paste, Saft einer halben Zitrone, 1 Schuss Essig, ein paar Jalapeño-Scheiben aus dem Glas, Salz, Pfeffer' },
    ],
    steps: [
      'Thunfisch abtropfen lassen und mit einer Gabel zerpflücken.',
      'Apfel, Zwiebel und Gewürzgurke klein würfeln und mit Mais, Skyr, Wasabi, Zitronensaft und Essig unterrühren.',
      'Mit Salz und Pfeffer abschmecken und die Jalapeños obendrauf legen.',
    ],
    tip: 'Wasabi und Zitrone statt Senf sind der Kniff aus dem Original: Sie geben Schärfe und Frische, ohne dass du viel Mayo brauchst. Erst wenig Wasabi nehmen und nachschärfen.',
  },
  egg_flight: {
    name: 'Egg Flight (Eier mit Toppings)', slot: 'snack', device: 'herd', alt: ['airfryer'], time: 5, proteins: ['ei', 'milch', 'fisch'], viral: true,
    ingredients: [
      { item: 'eier', amount: 3 },
      { item: 'huettenkaese', amount: 30 },
      { item: 'raeucherlachs', amount: 15 },
      { item: 'gewuerz', amount: 0, text: 'Schnittlauch, Dill, Sesam, Chiliflocken, ein paar Tropfen Sojasauce, Salz' },
    ],
    steps: [
      'Eier 9 Minuten kochen oder bei 150 °C 15 Minuten in den Airfryer, dann kalt abschrecken.',
      'Schälen, längs halbieren und in einer Reihe auf ein Brett legen.',
      'Zwei Hälften mit Hüttenkäse und Schnittlauch, zwei mit Räucherlachs und Dill, zwei mit Sojasauce, Sesam und Chiliflocken belegen.',
    ],
    tip: 'Wie bei einem Weinflight probierst du dich von mild nach würzig durch: Hüttenkäse zuerst, Chili zuletzt, so schmeckt jedes Ei anders.',
  },
  thunfischbrot: {
    name: '3-Zutaten-Thunfischbrot mit Hüttenkäse', slot: 'snack', device: 'airfryer', alt: ['ofen'], time: 5, proteins: ['fisch', 'ei', 'milch'], viral: true,
    ingredients: [
      { item: 'thunfisch', amount: 1 },
      { item: 'eier', amount: 1 },
      { item: 'huettenkaese', amount: 50 },
      { item: 'gewuerz', amount: 0, text: '½ TL Backpulver, Salz, Pfeffer, Knoblauchpulver, Schnittlauch' },
    ],
    steps: [
      'Thunfisch sehr gut abtropfen lassen und mit Ei, Backpulver und Gewürzen mit dem Pürierstab zu einem glatten Teig mixen.',
      'In eine kleine, mit Backpapier ausgelegte Form füllen und bei 170 °C etwa 15 Minuten in den Airfryer (Ofen: 180 °C, 25 Minuten).',
      'Fertig ist es, wenn ein Holzstäbchen trocken herauskommt. Kurz abkühlen lassen, in Scheiben schneiden und mit dem Hüttenkäse essen.',
    ],
    tip: 'Den Thunfisch richtig ausdrücken und glatt pürieren: Je trockener der Teig, desto mehr wird es Brot und desto weniger Omelett.',
  },
};
